import type { AuthorityChunk } from "../tax/authority/store";

// ── Federal tax CASE LAW (corpus-depth phase). Foundational doctrines, each WEB-VERIFIED and
// adversarially fact-checked (exact reporter citations confirmed against Cornell LII / Justia; holdings
// faithful, public-domain paraphrases) by the caselaw-ingest-verify workflow on 2026-06-25. These are
// EVERGREEN judicial doctrines (substance-over-form, the definition of gross income, "ordinary and
// necessary", the Cohan estimate rule, Crane debt-in-basis, INDOPCO capitalization), so each governs the
// full in-scope year range. They give the §6662 weight-of-authorities engine REAL court authority to weigh
// (a unanimous Supreme Court holding; a Second-Circuit holding) — the in-circuit-controlling-holding
// invariant was previously exercised only on synthetic inputs. authorityClass omitted: the case KIND
// weight (70) × the courtLevel multiplier (supreme 1.3 / circuit 1.15) ranks them per §1.6662-4.
const YEARS = [2024, 2025, 2026, 2027, 2028, 2029, 2030];
const INGESTED = "2026-06-25T00:00:00Z";

export const CORPUS_CASELAW: AuthorityChunk[] = [
  {
    chunkId: "case-gregory-v-helvering",
    authorityType: "case",
    citation: "Gregory v. Helvering, 293 U.S. 465 (1935)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1935-01-07",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/293/465",
    ingestedAt: INGESTED,
    text: "A taxpayer has the legal right to arrange affairs to minimize tax, but a transaction must be what it purports to be in substance, not merely in form. Although the taxpayer's transfer of corporate shares through a newly created corporation (which was then dissolved) literally satisfied the words of the reorganization statute, the maneuver served no business or corporate purpose and was an operation having no purpose other than to avoid tax by recasting an ordinary dividend distribution as a tax-favored reorganization. Because the transaction lacked any genuine business purpose and was a mere device masquerading as a corporate reorganization, the Court disregarded it and taxed the taxpayer as if she had simply received the underlying shares as a dividend. (Business-purpose / substance-over-form doctrine; the economic-substance doctrine was later partially codified at IRC §7701(o).)",
    keywords: ["economic substance","business purpose","substance over form","sham transaction","step transaction","gregory","7701(o)","reorganization"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-glenshaw-glass",
    authorityType: "case",
    citation: "Commissioner v. Glenshaw Glass Co., 348 U.S. 426 (1955)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1955-03-28",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/348/426",
    ingestedAt: INGESTED,
    text: "Construing the broad statutory definition of gross income as income 'from any source whatever' (then §22(a) of the 1939 Code, now IRC §61(a)), the Court held that Congress intended to tax all economic gains not specifically exempted. Gross income is NOT confined to gain derived from capital, from labor, or from both combined; it reaches 'undeniable accessions to wealth, clearly realized, and over which the taxpayers have complete dominion.' Applying that standard, the punitive (exemplary) portion of damages recovered in fraud and antitrust litigation was taxable income even though not derived from capital or labor. This is the governing definition of gross income.",
    keywords: ["gross income","accession to wealth","income from any source","punitive damages","glenshaw","complete dominion"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-welch-v-helvering",
    authorityType: "case",
    citation: "Welch v. Helvering, 290 U.S. 111 (1933)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1933-11-06",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/290/111",
    ingestedAt: INGESTED,
    text: "A business expense is deductible under the 'ordinary and necessary' standard (now IRC §162(a)) only if it is BOTH ordinary AND necessary. The Court (Justice Cardozo) treated 'necessary' as a low threshold: an expense is necessary when it is 'appropriate and helpful' to the taxpayer's business. But the taxpayer's voluntary payments of a bankrupt former employer's debts — made to rebuild his own reputation and credit — were not 'ordinary,' because people do not customarily pay the debts of others to whom they owe no legal obligation; such payments resemble capital outlays building goodwill. They were therefore not deductible as ordinary and necessary business expenses.",
    keywords: ["ordinary and necessary","appropriate and helpful","necessary expense","welch","162(a)"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-cohan-v-commissioner",
    authorityType: "case",
    citation: "Cohan v. Commissioner, 39 F.2d 540 (2d Cir. 1930)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1930-03-03",
    sourceUrl: "https://law.justia.com/cases/federal/appellate-courts/F2/39/540/1543179/",
    ingestedAt: INGESTED,
    text: "The 'Cohan rule': where a taxpayer's testimony and the surrounding facts convince the factfinder that deductible business expenses WERE in fact incurred, it is error to disallow the deductions entirely merely because the taxpayer kept no records and cannot prove exact amounts. The Board (now the Tax Court) should instead ESTIMATE the allowable amount, making as close an approximation as it can. Absolute certainty is usually impossible and is not required, but the estimate may bear heavily against the taxpayer whose own failure to keep records caused the uncertainty. (Note: by statute the Cohan estimate does NOT apply to expenses subject to the strict substantiation rules of IRC §274(d) — e.g., travel, meals, listed property.)",
    keywords: ["cohan","estimate","estimated","records","receipts","disallow","substantiation","approximation","274"],
    courtLevel: "circuit",
    circuit: "2",
    precedential: true,
  },
  {
    chunkId: "case-crane-v-commissioner",
    authorityType: "case",
    citation: "Crane v. Commissioner, 331 U.S. 1 (1947)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1947-04-14",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/331/1",
    ingestedAt: INGESTED,
    text: "When a taxpayer acquires real property subject to a nonrecourse mortgage the taxpayer does not personally assume, the unadjusted BASIS is the full fair market value of the property, undiminished by the mortgage (not merely the equity). Correspondingly, when the taxpayer later sells subject to that still-outstanding nonrecourse mortgage, the AMOUNT REALIZED includes the cash received PLUS the outstanding mortgage principal, because relief from the mortgage confers a real benefit equal to its amount. 'Property' means the physical property and the owner's rights in it, not merely net equity, so the mortgage is reflected on both the basis and amount-realized sides of the gain computation.",
    keywords: ["crane","nonrecourse","mortgage","1001","1012"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-indopco-v-commissioner",
    authorityType: "case",
    citation: "INDOPCO, Inc. v. Commissioner, 503 U.S. 79 (1992)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1992-03-24",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/503/79",
    ingestedAt: INGESTED,
    text: "Professional fees and similar expenses a corporation incurs in a friendly takeover are nondeductible CAPITAL expenditures, not ordinary and necessary business expenses. An expenditure need NOT create or enhance a separate and distinct asset to require capitalization; creating such an asset is a sufficient but not a necessary condition. The key factor is whether the taxpayer realizes benefits extending BEYOND the tax year of the expenditure. Because the acquisition produced significant long-term benefits, the costs had to be capitalized — deductions being narrowly construed exceptions to the norm of capitalization that the taxpayer must clearly establish.",
    keywords: ["indopco","capitalize","capitalized","capitalization","acquisition","merger","takeover","263"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-lucas-v-earl",
    authorityType: "case",
    citation: "Lucas v. Earl, 281 U.S. 111 (1930)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1930-01-01",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/281/111",
    ingestedAt: INGESTED,
    text: "Income from personal services is taxed to the individual who actually earned it and cannot be escaped by anticipatory contracts assigning it to someone else. A husband and wife's 1901 contract treating all of the husband's future earnings (salary and attorney's fees) as jointly held could not shift half of that income to the wife for tax purposes; the entire amount was taxable to the husband who earned it. As Justice Holmes wrote, the tax could not be escaped by \"anticipatory arrangements and contracts however skilfully devised,\" and no distinction can be drawn based on the arrangement by which the fruits are attributed to a different tree from that on which they grew.",
    keywords: ["lucas","earl","anticipatory","assignment of income","assign"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-helvering-v-horst",
    authorityType: "case",
    citation: "Helvering v. Horst, 311 U.S. 112 (1940)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1940-01-01",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/311/112",
    ingestedAt: INGESTED,
    text: "A bondholder who detached negotiable interest coupons from his bonds before their due date and gave them to his son as a gift remains taxable on that interest income when the coupons are later paid to the son. The Court held that the power to dispose of income is the equivalent of ownership of it, and the exercise of that power to direct payment of the income to another is itself the donor's enjoyment, and therefore the realization, of the income. Applying the \"fruit and the tree\" metaphor, the taxpayer could not attribute the fruit (the interest coupon) to a tree other than the one on which it grew (the underlying bond he kept), so the donor who controls the income is taxed on it.",
    keywords: ["horst","coupon","coupons","assignment of income"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-old-colony-trust-co-v-commissioner",
    authorityType: "case",
    citation: "Old Colony Trust Co. v. Commissioner, 279 U.S. 716 (1929)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1929-01-01",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/279/716",
    ingestedAt: INGESTED,
    text: "When an employer pays the income taxes owed by an employee as part of compensating the employee for services rendered, that tax payment is itself additional taxable income to the employee. The Court reasoned that the discharge by a third person of an obligation owed by the taxpayer is the equivalent of the taxpayer receiving that amount directly, and the benefit was derived from the employee's labor. The fact that the payment went straight to the government rather than into the employee's hands does not change its character as taxable gain.",
    keywords: ["old colony","employer pays","employer-paid","compensation"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-james-v-united-states",
    authorityType: "case",
    citation: "James v. United States, 366 U.S. 213 (1961)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1961-01-01",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/366/213",
    ingestedAt: INGESTED,
    text: "The Supreme Court held that money a taxpayer obtains unlawfully, including embezzled funds, is taxable gross income to the wrongdoer in the year it is received, even though the taxpayer may be legally obligated to repay it. Such gains fall within the broad statutory definition of gross income under Section 22(a) of the 1939 Code (\"gains or profits and income derived from any source whatever\") and Section 61(a) of the 1954 Code (\"all income from whatever source derived\"). Income exists where the taxpayer has an accession to wealth, clearly realized, over which he has complete dominion. The Court overruled Commissioner v. Wilcox, 327 U.S. 404 (1946), which had exempted embezzled funds.",
    keywords: ["james","illegal","illegally","embezzled","embezzlement"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-commissioner-of-internal-revenue-v-duberstein",
    authorityType: "case",
    citation: "Commissioner of Internal Revenue v. Duberstein, 363 U.S. 278 (1960)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1960-01-01",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/363/278",
    ingestedAt: INGESTED,
    text: "To qualify as a tax-free gift excluded from gross income, a transfer must proceed from \"detached and disinterested generosity,\" given out of affection, respect, admiration, charity, or like impulses. A transfer is not a gift if it instead proceeds primarily from the constraining force of a moral or legal duty or from the incentive of anticipated economic benefit; thus a transfer made from a business motive is not a gift. Whether a transfer is a gift turns on the transferor's dominant intention, determined by the trier of fact through an objective inquiry into the totality of the circumstances and the mainsprings of human conduct, not by any single bright-line rule.",
    keywords: ["gift","duberstein","detached","disinterested","generosity","income","exclude","exclusion","business","motive","tip","bonus","intent","section102","102","gross"],
    courtLevel: "supreme",
    precedential: true,
  },
  {
    chunkId: "case-north-american-oil-consolidated-v-burnet",
    authorityType: "case",
    citation: "North American Oil Consolidated v. Burnet, 286 U.S. 417 (1932)",
    jurisdiction: "federal",
    taxYear: YEARS,
    effectiveDate: "1932-01-01",
    sourceUrl: "https://www.law.cornell.edu/supremecourt/text/286/417",
    ingestedAt: INGESTED,
    text: "Income received under a claim of right and without restriction as to its disposition is taxable in the year received, even if the taxpayer's right to retain the money is still disputed and even if the taxpayer may later be adjudged liable to restore its equivalent. Here, profits a receiver collected in 1916 from disputed oil-land operations became taxable to the company in 1917, the year the lower court held the company entitled to them and the funds were paid over without restriction. A later reversal would not change the year of taxation; if the taxpayer is ultimately forced to repay, a deduction is taken in the year of repayment rather than restating the earlier income.",
    keywords: ["north american oil","claim of right","restriction","repay"],
    courtLevel: "supreme",
    precedential: true,
  },];
