// AUTO-GENERATED by scripts/ingest-authority.mts — re-run to refresh; do not hand-edit.
// Grounded primary-authority chunks: each is a concise operative-rule paraphrase produced
// FROM the fetched source text, and every $/%/year figure was verified to appear in that
// source before admission. Public domain (statute) — §7216-clean. Registered in authority/store.ts.
import type { AuthorityChunk } from "../tax/authority/store";

export const CORPUS_INGESTED: AuthorityChunk[] = [
  {
    "chunkId": "ingested-irc-3121",
    "authorityType": "statute",
    "citation": "IRC §3121",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/3121",
    "ingestedAt": "2026-06-24T09:19:16.876Z",
    "text": "Under IRC §3121(a), 'wages' for FICA purposes means all remuneration for employment, including the cash value of remuneration paid in any medium other than cash, subject to enumerated exclusions. Cash tips received by an employee in any calendar month are included in wages—and therefore subject to employer and employee FICA taxes under Chapter 21—unless the amount of such cash tips in that month is less than $20; tips paid in any medium other than cash are excluded from wages entirely. Because tips meeting the $20-per-month threshold are FICA wages processed through the employer's payroll, they are not subject to self-employment tax. The Social Security wage base cap applies to the taxes imposed under §§3101(a) and 3111(a) once remuneration paid by a single employer equals the contribution and benefit base determined under §230 of the Social Security Act for that calendar year.",
    "keywords": [
      "irc 3121",
      "fica wages",
      "tips as wages",
      "cash tips",
      "twenty dollar tip threshold",
      "employment definition",
      "payroll fica",
      "self-employment tax exclusion",
      "contribution and benefit base",
      "social security wage base",
      "remuneration",
      "chapter 21",
      "tip income",
      "employer fica",
      "employee fica"
    ]
  },
  {
    "chunkId": "ingested-irc-1402",
    "authorityType": "statute",
    "citation": "IRC §1402",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1402",
    "ingestedAt": "2026-06-24T09:19:26.191Z",
    "text": "Under IRC §1402, 'net earnings from self-employment' means gross income from a trade or business carried on by an individual, less allowable deductions attributable to that trade or business, plus the individual's distributive share of ordinary income or loss from a partnership trade or business. Certain items are excluded from this base, including real estate rentals (unless received as a dealer), dividends and interest (unless received by a dealer in stocks or securities), capital gains and losses, and a limited partner's distributive share of partnership income other than guaranteed payments for services actually rendered. The term 'self-employment income' (the SE-tax base) does not include net earnings below $400, and for the OASDI portion under §1401(a) it is capped by reducing the contribution and benefit base (as determined under §230 of the Social Security Act) by wages already paid to the individual during the taxable year. W-2 wages and tips received as an employee are thus excluded from the SE-tax base because employee service is expressly carved out of the definition of 'trade or business' for self-employment purposes.",
    "keywords": [
      "irc 1402",
      "net earnings from self-employment",
      "self-employment income",
      "se tax base",
      "trade or business",
      "limited partner exclusion",
      "guaranteed payments",
      "contribution and benefit base",
      "wages offset",
      "real estate rental exclusion",
      "capital gain exclusion",
      "partnership distributive share",
      "400 dollar threshold",
      "employee exclusion",
      "self-employment tax"
    ]
  },
  {
    "chunkId": "ingested-irc-1401",
    "authorityType": "statute",
    "citation": "IRC §1401",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2013-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1401",
    "ingestedAt": "2026-06-24T09:19:35.051Z",
    "text": "Under IRC §1401, self-employment income is subject to two separate taxes each taxable year: (1) an OASDI (old-age, survivors, and disability insurance) tax of 12.4 percent of self-employment income, and (2) a hospital insurance (Medicare) tax of 2.9 percent of self-employment income. In addition, for taxable years beginning after December 31, 2012, an additional 0.9 percent Medicare tax applies to self-employment income exceeding $250,000 for joint filers, $200,000 for single and other filers, or one-half of the joint-return threshold for married filing separately. The $250,000 and $200,000 thresholds are each reduced (but not below zero) by wages already taken into account for the additional Medicare tax under section 3121(b)(2). Self-employment income covered exclusively by a foreign country's social security system under an agreement authorized by section 233 of the Social Security Act is exempt from these taxes.",
    "keywords": [
      "irc section 1401",
      "self-employment tax",
      "oasdi",
      "social security tax",
      "medicare tax",
      "hospital insurance",
      "12.4 percent",
      "2.9 percent",
      "0.9 percent additional medicare tax",
      "self-employment income",
      "net investment income",
      "high-income threshold",
      "totalization agreement",
      "chapter 2 tax"
    ]
  },
  {
    "chunkId": "ingested-irc-61",
    "authorityType": "statute",
    "citation": "IRC §61",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2019-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/61",
    "ingestedAt": "2026-06-24T09:19:51.903Z",
    "text": "Under IRC §61(a), gross income means all income from whatever source derived, except as otherwise provided in Subtitle A of the Code. The definition is broad and inclusive, encompassing (but not limited to) compensation for services (including fees, commissions, and fringe benefits), gross income from business, gains from dealings in property, interest, rents, royalties, dividends, annuities, income from life insurance and endowment contracts, pensions, income from discharge of indebtedness, a distributive share of partnership gross income, income in respect of a decedent, and income from an interest in an estate or trust. Items specifically included in gross income are addressed in Part II (§71 and following), while items specifically excluded are addressed in Part III (§101 and following). A tax preparer should presume any accession to wealth is gross income unless a specific statutory exclusion applies.",
    "keywords": [
      "irc §61",
      "gross income defined",
      "all income from whatever source derived",
      "compensation for services",
      "fringe benefits",
      "discharge of indebtedness",
      "distributive share partnership",
      "income in respect of a decedent",
      "dividends interest rents royalties",
      "exclusions from gross income",
      "inclusions in gross income",
      "annuities pensions",
      "gains from property dealings",
      "subtitle a chapter 1"
    ]
  },
  {
    "chunkId": "ingested-irc-62",
    "authorityType": "statute",
    "citation": "IRC §62",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/62",
    "ingestedAt": "2026-06-24T09:20:03.663Z",
    "text": "Under IRC §62, an individual's adjusted gross income (AGI) equals gross income reduced by specific 'above-the-line' deductions taken before any standard or itemized deduction. Allowable above-the-line deductions include: trade or business expenses (other than employee services), reimbursed employee business expenses under a qualifying arrangement, certain performing-artist and state/local-official expenses, eligible-educator classroom expenses (up to $250, inflation-adjusted for years after 2015 in $50 increments), Armed Forces reservist travel expenses for assignments more than 100 miles from home, losses from property sales, rental and royalty expenses, depreciation for life tenants and trust income beneficiaries, self-employed retirement plan contributions (§404), IRA deductions (§219), early-withdrawal penalties on time deposits, reforestation expenses (§194), jury-duty pay remitted to an employer, moving expenses (§217), Archer MSA deductions (§220), education-loan interest (§221), health savings account deductions (§223), attorney fees and court costs in unlawful-discrimination or whistleblower-award actions (capped at the gross income inclusion from the judgment or award), and supplemental unemployment compensation repayments. The §199A deduction is explicitly excluded from all of the above categories, and no item may be deducted more than once.",
    "keywords": [
      "irc §62",
      "adjusted gross income",
      "above-the-line deductions",
      "eligible educator",
      "performing artist",
      "self-employed retirement",
      "health savings account",
      "education loan interest",
      "archer msa",
      "reimbursed employee expenses",
      "whistleblower attorney fees",
      "reservist travel expenses",
      "jury duty pay",
      "inflation adjustment"
    ]
  },
  {
    "chunkId": "ingested-irc-213",
    "authorityType": "statute",
    "citation": "IRC §213",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2021-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/213",
    "ingestedAt": "2026-06-24T09:20:12.911Z",
    "text": "A taxpayer may deduct unreimbursed expenses paid during the taxable year for medical care of the taxpayer, spouse, or qualifying dependent, but only to the extent those expenses exceed 7.5 percent of adjusted gross income. 'Medical care' covers amounts paid for diagnosis, cure, mitigation, treatment, or prevention of disease; transportation essential to such care; qualified long-term care services; and qualifying insurance premiums—but expressly excludes cosmetic surgery unless required to correct a congenital abnormality, accident-related injury, or disfiguring disease. For medicine and drugs, only prescribed drugs and insulin qualify. Lodging away from home while receiving medical care from a physician in a licensed hospital may be included, but the deductible lodging amount is capped at $50 per night per individual. Any expense already allowed as a credit under IRC §21 may not also be deducted as a medical expense.",
    "keywords": [
      "irc 213",
      "medical expense deduction",
      "7.5 percent agi floor",
      "adjusted gross income threshold",
      "unreimbursed medical expenses",
      "prescribed drugs",
      "qualified long-term care",
      "cosmetic surgery exclusion",
      "lodging medical care",
      "medical care definition",
      "insulin",
      "dependent medical expenses",
      "insurance premiums medical care",
      "schedule a itemized deduction"
    ]
  },
  {
    "chunkId": "ingested-irc-223",
    "authorityType": "statute",
    "citation": "IRC §223",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/223",
    "ingestedAt": "2026-06-24T09:20:23.946Z",
    "text": "An eligible individual covered by a high deductible health plan (HDHP) on the first day of a month may deduct cash contributions made to a health savings account (HSA), limited to 1/12 of $2,250 (self-only coverage) or $4,500 (family coverage) for each month of eligibility; an individual who has attained age 55 before the close of the taxable year may contribute an additional amount up to $1,000 per year (as phased in by the statute's table). An HDHP must have an annual deductible of at least $1,000 for self-only coverage (twice that for family coverage) and total annual out-of-pocket expenses not exceeding $5,000 for self-only coverage (twice that for family coverage). The annual limit is reduced dollar-for-dollar by Archer MSA contributions, employer contributions excludable under §106(d), and IRA-to-HSA rollovers under §408(d)(9); a dependent who may be claimed on another taxpayer's return is ineligible for the deduction, and the limit drops to zero for any month the individual is enrolled in Medicare. Distributions used exclusively for qualified medical expenses are excluded from gross income, while non-qualifying distributions are included in gross income and subject to an additional 20-percent tax, with exceptions for death or disability.",
    "keywords": [
      "irc §223",
      "health savings account",
      "hsa deduction",
      "high deductible health plan",
      "hdhp",
      "eligible individual",
      "contribution limit",
      "self-only coverage",
      "family coverage",
      "catch-up contribution",
      "age 55",
      "qualified medical expenses",
      "archer msa coordination",
      "medicare ineligibility",
      "20 percent additional tax"
    ]
  },
  {
    "chunkId": "ingested-irc-219",
    "authorityType": "statute",
    "citation": "IRC §219",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/219",
    "ingestedAt": "2026-06-24T09:20:37.845Z",
    "text": "Under IRC §219, an individual may deduct qualified retirement contributions (cash amounts paid to an individual retirement plan) for the taxable year, limited to the lesser of (a) the deductible amount—a base dollar figure of $5,000 indexed for cost-of-living after 2008 in $500 increments—or (b) the individual's compensation includible in gross income for the year. Individuals who have attained age 50 before the close of the taxable year may increase the deductible amount by $1,000 (itself indexed for cost-of-living after 2023 in $100 increments). A non-working or lower-earning spouse filing jointly may use the higher-earning spouse's compensation to determine the deductible amount under the Kay Bailey Hutchison Spousal IRA rules. If the individual (or their spouse) is an active participant in an employer-sponsored retirement plan for any part of a plan year ending within the taxable year, the deductible amount is phased out ratably over a $10,000 AGI range ($20,000 for joint filers) above an applicable dollar threshold—$80,000 for joint filers, $50,000 for single filers, and zero for married filing separately—each threshold indexed in $1,000 increments after 2006; a non-active-participant spouse of an active participant has a separate, higher applicable dollar amount of $150,000 phased out over $10,000.",
    "keywords": [
      "irc 219",
      "deductible ira contribution",
      "qualified retirement contribution",
      "individual retirement plan",
      "catch-up contribution",
      "active participant",
      "phase-out",
      "spousal ira",
      "kay bailey hutchison",
      "applicable dollar amount",
      "cost-of-living adjustment",
      "compensation",
      "adjusted gross income",
      "traditional ira deduction",
      "retirement savings"
    ]
  },
  {
    "chunkId": "ingested-irc-163",
    "authorityType": "statute",
    "citation": "IRC §163",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2018-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/163",
    "ingestedAt": "2026-06-24T09:20:45.745Z",
    "text": "Under IRC §163(a), all interest paid or accrued within the taxable year on indebtedness is generally deductible. For individual taxpayers, 'personal interest' is disallowed, but 'qualified residence interest' is excepted and remains deductible; qualified residence interest includes interest on acquisition indebtedness (debt incurred to acquire, construct, or substantially improve a qualified residence and secured by it) up to a $1,000,000 aggregate limit ($500,000 for married filing separately) for indebtedness incurred on or before December 15, 2017, and up to $750,000 ($375,000 for married filing separately) for indebtedness incurred after December 15, 2017, with home equity indebtedness interest disallowed for taxable years beginning after December 31, 2017. Investment interest deductions for non-corporate taxpayers are limited to net investment income for the taxable year, with any disallowed amount carried forward to the succeeding taxable year.",
    "keywords": [
      "irc §163",
      "interest deduction",
      "qualified residence interest",
      "acquisition indebtedness",
      "home equity indebtedness",
      "mortgage interest",
      "personal interest disallowance",
      "investment interest limitation",
      "net investment income",
      "750000 limit",
      "1000000 limit",
      "married filing separately",
      "carryforward disallowed interest",
      "taxable year 2024 2025"
    ]
  },
  {
    "chunkId": "ingested-irc-6662",
    "authorityType": "statute",
    "citation": "IRC §6662",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/6662",
    "ingestedAt": "2026-06-24T09:20:57.774Z",
    "text": "Under IRC §6662, a 20% accuracy-related penalty is added to the tax on any portion of an underpayment attributable to negligence or disregard of rules, a substantial understatement of income tax, a substantial valuation misstatement, a substantial overstatement of pension liabilities, a substantial estate or gift tax valuation understatement, a transaction lacking economic substance, an undisclosed foreign financial asset understatement, an inconsistent estate basis, an overstatement of the section 170(p) deduction, or a disallowance under section 170(h)(7). A substantial understatement of income tax exists when the understatement exceeds the greater of 10% of the tax required to be shown on the return or $5,000 (for corporations other than S corporations or personal holding companies, the threshold is the lesser of 10% of tax required or $10,000, but at least $10,000, capped at $10,000,000; for taxpayers claiming a section 199A deduction, the 10% threshold is reduced to 5%). The penalty rate is increased to 40% for gross valuation misstatements, nondisclosed noneconomic substance transactions, and undisclosed foreign financial asset understatements, and to 50% for overstatements of the section 170(p) deduction. The understatement amount is reduced for positions supported by substantial authority or adequately disclosed items with a reasonable basis, but this reduction does not apply to tax shelter items. No §6662 penalty applies to any portion of an underpayment already subject to the fraud penalty under §6663 or, generally, to reportable transaction understatements subject to §6662A.",
    "keywords": [
      "irc 6662",
      "accuracy-related penalty",
      "underpayment",
      "substantial understatement",
      "negligence",
      "valuation misstatement",
      "20 percent penalty",
      "40 percent penalty",
      "tax shelter",
      "substantial authority",
      "section 199a",
      "economic substance",
      "foreign financial asset",
      "gross valuation misstatement",
      "income tax understatement threshold"
    ]
  },
  {
    "chunkId": "ingested-irc-6651",
    "authorityType": "statute",
    "citation": "IRC §6651",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2020-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/6651",
    "ingestedAt": "2026-06-24T09:21:08.702Z",
    "text": "Under IRC §6651, a taxpayer who fails to file a required return by the prescribed due date (including extensions) is subject to an addition to tax of 5 percent of the net tax due for each month or fraction thereof the return is late, up to a maximum of 25 percent; if the failure is fraudulent, the rate rises to 15 percent per month with a 75 percent cap. A separate failure-to-pay penalty of 0.5 percent per month (maximum 25 percent) applies to unpaid tax shown on a return, reduced to 0.25 percent per month during any month an installment agreement under §6159 is in effect; that rate increases to 1 percent per month after IRS issues a levy notice under §6331(d) or demands immediate payment under §6331(a). When both failure-to-file and failure-to-pay penalties apply in the same month, the failure-to-file addition is reduced by the failure-to-pay amount for that month. For chapter 1 income tax returns filed more than 60 days late, the failure-to-file penalty is at least the lesser of $435 (subject to cost-of-living adjustment for returns required to be filed in calendar years after 2020) or 100 percent of the tax required to be shown, unless the failure is due to reasonable cause and not willful neglect; these penalties do not apply to failures to pay estimated tax.",
    "keywords": [
      "irc 6651",
      "failure to file penalty",
      "failure to pay penalty",
      "5 percent per month",
      "0.5 percent per month",
      "25 percent maximum",
      "reasonable cause",
      "willful neglect",
      "installment agreement reduction",
      "fraudulent failure to file",
      "minimum penalty",
      "cost-of-living adjustment",
      "levy notice",
      "estimated tax exception",
      "net amount due"
    ]
  },
  {
    "chunkId": "ingested-irc-6694",
    "authorityType": "statute",
    "citation": "IRC §6694",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026,
      2027,
      2028,
      2029,
      2030
    ],
    "effectiveDate": "2016-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/6694",
    "ingestedAt": "2026-06-24T09:21:18.524Z",
    "text": "A tax return preparer who prepares a return or refund claim containing an understatement of liability due to an unreasonable position (one lacking substantial authority, or lacking a reasonable basis if disclosed, or failing the more-likely-than-not standard for tax shelters and section 6662A reportable transactions) and who knew or should have known of that position must pay a penalty equal to the greater of $1,000 or 50 percent of the income derived from that return or claim, unless reasonable cause and good faith are shown. If the understatement results from willful or reckless conduct—including a willful attempt to understate tax or reckless/intentional disregard of rules—the penalty rises to the greater of $5,000 or 75 percent of the income derived, reduced by any amount already paid under the unreasonable-position penalty. A preparer may suspend collection of the full penalty by paying at least 15 percent within 30 days of notice and demand and filing a refund claim, then timely bringing suit in U.S. district court. If a final administrative or judicial determination establishes there was no understatement, any assessed penalty is abated and amounts paid are refunded. For an UNDISCLOSED non-tax-shelter position the preparer needs SUBSTANTIAL AUTHORITY (the same standard, roughly a 40% likelihood, that supports the taxpayer's §6662 substantial-understatement defense); a position is DISCLOSED by attaching Form 8275 (or Form 8275-R if contrary to a regulation), which lowers the required standard to REASONABLE BASIS for both the §6694 preparer penalty and the taxpayer's §6662 penalty. So a position with reasonable basis but not substantial authority (e.g. roughly a 35% chance of winning) is protected for both preparer and client by disclosing it on Form 8275.",
    "keywords": [
      "irc 6694",
      "section 6694",
      "tax return preparer",
      "understatement penalty",
      "unreasonable position",
      "substantial authority",
      "willful reckless conduct",
      "preparer penalty",
      "reasonable cause good faith",
      "tax shelter reportable transaction",
      "more likely than not",
      "reasonable basis",
      "disclosed position",
      "undisclosed",
      "form 8275",
      "adequate disclosure",
      "preparer",
      "taxpayer",
      "exposure",
      "understatement of liability",
      "6662a"
    ]
  },
  {
    "chunkId": "ingested-irc-7216",
    "authorityType": "statute",
    "citation": "IRC §7216",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "1989-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/7216",
    "ingestedAt": "2026-06-24T09:21:24.666Z",
    "text": "Under IRC §7216, any person engaged in the business of preparing income tax returns under chapter 1, or who prepares such returns for compensation, commits a misdemeanor if they knowingly or recklessly disclose or use for any unauthorized purpose information furnished in connection with return preparation. Upon conviction, the penalty is a fine of not more than $1,000—or not more than $100,000 where section 6713(b) applies—or imprisonment of not more than 1 year, or both, plus costs of prosecution. Exceptions exist for disclosures required by other provisions of the Code or court order, use of information to prepare state/local tax returns for the same taxpayer, and disclosures or uses permitted by Treasury regulations (including quality or peer reviews).",
    "keywords": [
      "irc §7216",
      "section 7216",
      "tax preparer",
      "return information",
      "disclosure",
      "unauthorized use",
      "misdemeanor",
      "criminal penalty",
      "fine",
      "imprisonment",
      "chapter 1 returns",
      "section 6713(b)",
      "peer review",
      "confidentiality",
      "return preparation"
    ]
  },
  {
    "chunkId": "ingested-irc-6050w",
    "authorityType": "statute",
    "citation": "IRC §6050W",
    "jurisdiction": "federal",
    "taxYear": [
      2025,
      2026
    ],
    "effectiveDate": "2025-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/6050W",
    "ingestedAt": "2026-06-25T02:33:05.866Z",
    "text": "Under IRC §6050W, every payment settlement entity must file an annual information return reporting the name, address, TIN, and gross amount of reportable payment transactions for each participating payee. Merchant acquiring entities must report all payment card transactions with no de minimis threshold. Third party settlement organizations, however, are required to report third party network transactions for a participating payee only if (1) the gross amount of those transactions exceeds $20,000 and (2) the aggregate number of such transactions exceeds 200; if either threshold is not met, no reporting is required. The 2025 amendment (Pub. L. 119–21, §70432) restored these dual $20,000/200-transaction thresholds, effective as if included in the American Rescue Plan Act of 2021. A written payee statement must be furnished on or before January 31 of the year following the calendar year for which the return was required.",
    "keywords": [
      "6050w",
      "1099-k",
      "third party settlement organization",
      "payment card transaction",
      "merchant acquiring entity",
      "de minimis threshold",
      "$20,000",
      "200 transactions",
      "gross amount",
      "reportable payment transaction",
      "third party network transaction",
      "obbba",
      "participating payee",
      "information return",
      "payment settlement entity"
    ]
  },
  {
    "chunkId": "ingested-irc-174a",
    "authorityType": "statute",
    "citation": "IRC §174A",
    "jurisdiction": "federal",
    "taxYear": [
      2025,
      2026
    ],
    "effectiveDate": "2025-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/174A",
    "ingestedAt": "2026-06-25T02:33:15.429Z",
    "text": "Under IRC §174A, a taxpayer may deduct domestic research or experimental expenditures—those paid or incurred in connection with a trade or business and not attributable to foreign research within the meaning of §41(d)(4)(F)—in full in the taxable year paid or incurred, notwithstanding §263. Software development costs are treated as research or experimental expenditures for this purpose. As an alternative, the taxpayer may elect to capitalize such expenditures and amortize them ratably over a period of not less than 60 months, beginning with the month benefits are first realized; once made, that election and the chosen period bind all subsequent taxable years unless the Secretary approves a change. The section does not apply to land acquisition or improvement, depreciable or depletable property used in research, or mineral/oil-and-gas exploration expenditures. This provision applies to amounts paid or incurred in taxable years beginning after December 31, 2024, with a transition election available for certain small businesses to apply it retroactively to taxable years beginning after December 31, 2021.",
    "keywords": [
      "irc §174a",
      "section 174a",
      "domestic research expenditures",
      "experimental expenditures",
      "current expensing",
      "r&d deduction",
      "amortization election",
      "60-month amortization",
      "software development",
      "foreign research exclusion",
      "obbba",
      "taxable years beginning after december 31 2024",
      "small business retroactive election",
      "unamortized amounts",
      "trade or business"
    ]
  },
  {
    "chunkId": "ingested-irc-1361",
    "authorityType": "statute",
    "citation": "IRC §1361",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1361",
    "ingestedAt": "2026-06-27T01:39:59.516Z",
    "text": "For IRC §1361, an S corporation is a small business corporation for which a §1362(a) election is in effect for the taxable year; a C corporation is any corporation that is not an S corporation for that year. A small business corporation is a domestic corporation that is not an ineligible corporation and that does not have more than 100 shareholders, an impermissible nonindividual shareholder, a nonresident alien shareholder, or more than 1 class of stock. Permitted nonindividual shareholders include estates, trusts described in §1361(c)(2), and organizations described in §1361(c)(6); differences in voting rights among shares of common stock alone do not create more than 1 class of stock.",
    "keywords": [
      "irc 1361",
      "s corporation",
      "small business corporation",
      "1362 election",
      "domestic corporation",
      "100 shareholders",
      "eligible shareholders",
      "nonresident alien",
      "one class of stock",
      "voting rights",
      "trust shareholder",
      "estate shareholder",
      "exempt organization"
    ]
  },
  {
    "chunkId": "ingested-irc-1366",
    "authorityType": "statute",
    "citation": "IRC §1366",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1983-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1366",
    "ingestedAt": "2026-06-27T01:40:27.767Z",
    "text": "Under IRC § 1366, an S corporation shareholder determines tax liability by taking into account the shareholder’s pro rata share of the corporation’s separately stated items of income, tax-exempt income, loss, deduction, or credit that could affect shareholder tax liability, plus nonseparately computed income or loss. The character of each passed-through item is determined as if the shareholder realized it directly from the corporation’s source or incurred it in the same manner as the corporation. A shareholder’s aggregate losses and deductions for a taxable year may not exceed the sum of the adjusted basis of the shareholder’s S corporation stock and the adjusted basis of any S corporation indebtedness to the shareholder; disallowed losses or deductions are treated as incurred by the corporation in the succeeding taxable year with respect to that shareholder.",
    "keywords": [
      "irc 1366",
      "section 1366",
      "s corporation",
      "shareholder",
      "pass-through",
      "pro rata share",
      "separately stated items",
      "nonseparately computed income",
      "loss limitation",
      "stock basis",
      "debt basis",
      "disallowed losses",
      "carryover"
    ]
  },
  {
    "chunkId": "ingested-irc-1367",
    "authorityType": "statute",
    "citation": "IRC §1367",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2015-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1367",
    "ingestedAt": "2026-06-27T01:40:58.046Z",
    "text": "For each period, an S corporation shareholder increases stock basis by the shareholder’s income items under section 1366(a)(1)(A), nonseparately computed income, and excess depletion deductions over the basis of the depleted property. The shareholder decreases stock basis, but not below zero, by nonincluded distributions under section 1368, loss and deduction items under section 1366(a)(1)(A), nonseparately computed loss, nondeductible noncapital expenses, and specified oil and gas depletion; for a charitable contribution of property, the decrease is the shareholder’s pro rata share of the property’s adjusted basis. If the loss, deduction, nondeductible expense, and depletion decreases exceed stock basis, the excess reduces, but not below zero, the shareholder’s basis in S corporation indebtedness to the shareholder; later net increases restore that debt-basis reduction before increasing stock basis. Income items count only to the extent included in the shareholder’s gross income on the return, as adjusted by any redetermination.",
    "keywords": [
      "1367",
      "s corporation",
      "shareholder basis",
      "stock basis",
      "debt basis",
      "basis adjustments",
      "income items",
      "loss deductions",
      "distributions",
      "nondeductible expenses",
      "depletion",
      "charitable contribution",
      "section 1366",
      "section 1368"
    ]
  },
  {
    "chunkId": "ingested-irc-1368",
    "authorityType": "statute",
    "citation": "IRC §1368",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1983-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1368",
    "ingestedAt": "2026-06-27T01:41:27.817Z",
    "text": "Under IRC §1368, an S corporation distribution of property with respect to its stock that otherwise would be governed by section 301(c) is taxed under the S corporation distribution rules. If the S corporation has no accumulated earnings and profits, the distribution is excluded from gross income to the extent it does not exceed the shareholder’s adjusted stock basis, and any excess is treated as gain from the sale or exchange of property. If the S corporation has accumulated earnings and profits, the distribution is first applied against the accumulated adjustments account and treated under the stock-basis rule, then treated as a dividend to the extent of accumulated earnings and profits, and any remaining amount is again treated under the stock-basis rule. Stock basis and the accumulated adjustments account are determined with the adjustments specified in sections 1367 and 1368.",
    "keywords": [
      "irc 1368",
      "s corporation",
      "distributions",
      "accumulated earnings and profits",
      "accumulated adjustments account",
      "stock basis",
      "gross income exclusion",
      "dividend",
      "capital gain",
      "section 301(c)",
      "section 1367",
      "aaa ordering"
    ]
  },
  {
    "chunkId": "ingested-irc-1374",
    "authorityType": "statute",
    "citation": "IRC §1374",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2015-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1374",
    "ingestedAt": "2026-06-27T01:41:56.252Z",
    "text": "IRC §1374 imposes a corporate-level tax when, for a taxable year beginning in the recognition period, an S corporation has net recognized built-in gain. The tax is computed by applying the highest rate of tax specified in section 11(b) to the S corporation’s net recognized built-in gain for the taxable year. The recognition period is the 5-year period beginning with the first day of the first taxable year for which the corporation was an S corporation, and the tax does not apply to a corporation that has had a section 1362(a) S election in effect for each taxable year. For assets acquired from a C corporation with carryover basis, the rule applies to net recognized built-in gain attributable to those assets during a recognition period measured by reference to the asset acquisition day.",
    "keywords": [
      "irc 1374",
      "section 1374",
      "built-in gains tax",
      "s corporation",
      "c corporation",
      "recognition period",
      "net recognized built-in gain",
      "section 11(b)",
      "corporate rate",
      "carryover basis",
      "section 1362 election",
      "net unrealized built-in gain"
    ]
  },
  {
    "chunkId": "ingested-irc-704",
    "authorityType": "statute",
    "citation": "IRC §704",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2018-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/704",
    "ingestedAt": "2026-06-27T01:47:25.268Z",
    "text": "A partner’s distributive share of partnership income, gain, loss, deduction, or credit is determined by the partnership agreement, except as otherwise provided in chapter 1. If the agreement does not provide for the item, or if the agreement’s allocation lacks substantial economic effect, the item is determined according to the partner’s interest in the partnership based on all facts and circumstances. For contributed property, income, gain, loss, and deduction are allocated to account for the difference between the partnership’s basis and the property’s fair market value at contribution, including special rules for built-in loss and certain distributions within 7 years. A partner may deduct partnership losses, including capital losses, only to the extent of the adjusted basis of the partner’s partnership interest at the end of the partnership year, with excess loss allowed under the statutory carryover rule.",
    "keywords": [
      "704",
      "irc 704",
      "partner distributive share",
      "partnership agreement",
      "substantial economic effect",
      "partner interest",
      "contributed property",
      "built-in gain",
      "built-in loss",
      "adjusted basis",
      "loss limitation",
      "carryover",
      "partnership loss",
      "fair market value"
    ]
  },
  {
    "chunkId": "ingested-irc-705",
    "authorityType": "statute",
    "citation": "IRC §705",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1975-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/705",
    "ingestedAt": "2026-06-27T01:47:56.724Z",
    "text": "Except as provided by the alternative rule in subsection (b), a partner’s adjusted basis in a partnership interest is the basis determined under section 722 for contributions or section 742 for transfers. Increase that basis by the partner’s distributive share for the taxable year and prior taxable years of partnership taxable income under section 703(a), tax-exempt income, and the excess of depletion deductions over the basis of the property subject to depletion. Decrease the basis, but not below zero, by partnership distributions under section 733 and by the partner’s distributive share for the taxable year and prior taxable years of partnership losses and nondeductible expenditures not properly chargeable to capital account; also decrease it, but not below zero, by the partner’s depletion deduction for partnership oil and gas property to the extent specified by section 613A(c)(7)(D). Regulations may permit adjusted basis to be determined by reference to the partner’s proportionate share of the adjusted basis of partnership property upon a partnership termination.",
    "keywords": [
      "irc 705",
      "section 705",
      "partner basis",
      "outside basis",
      "partnership interest",
      "distributive share",
      "taxable income",
      "tax-exempt income",
      "partnership losses",
      "distributions",
      "nondeductible expenditures",
      "depletion",
      "section 722",
      "section 742",
      "section 733"
    ]
  },
  {
    "chunkId": "ingested-irc-722",
    "authorityType": "statute",
    "citation": "IRC §722",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/722",
    "ingestedAt": "2026-06-27T01:48:17.959Z",
    "text": "Under IRC § 722, a partner’s basis in a partnership interest acquired by contributing property, including money, to the partnership equals the amount of money contributed plus the partner’s adjusted basis in the contributed property at the time of contribution. That basis is increased by any gain recognized by the contributing partner under section 721(b) at that time.",
    "keywords": [
      "irc 722",
      "section 722",
      "partner basis",
      "partnership interest",
      "contributing partner",
      "property contribution",
      "money contribution",
      "adjusted basis",
      "time of contribution",
      "section 721(b)",
      "recognized gain",
      "subchapter k"
    ]
  },
  {
    "chunkId": "ingested-irc-731",
    "authorityType": "statute",
    "citation": "IRC §731",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1997-08-05",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/731",
    "ingestedAt": "2026-06-27T01:48:47.738Z",
    "text": "On a partnership distribution to a partner, the partner recognizes no gain except to the extent money distributed exceeds the partner’s adjusted basis in the partnership interest immediately before the distribution; for this gain rule, money includes marketable securities taken at fair market value on the distribution date. The partner recognizes no loss except on a liquidation of the partner’s interest where only money, section 751(c) unrealized receivables, and section 751(d) inventory are distributed, and then only to the extent the partner’s adjusted basis exceeds the sum of the money distributed and the section 732 basis of those receivables and inventory. Gain or loss recognized under this rule is treated as from the sale or exchange of the distributee partner’s partnership interest, and the partnership recognizes no gain or loss on a distribution of property, including money. Section 731 is subject to exceptions under sections 736, 751, and 737.",
    "keywords": [
      "irc 731",
      "section 731",
      "partnership distribution",
      "partner gain",
      "partner loss",
      "money distributed",
      "outside basis",
      "liquidating distribution",
      "marketable securities",
      "unrealized receivables",
      "inventory",
      "section 732",
      "section 751"
    ]
  },
  {
    "chunkId": "ingested-irc-752",
    "authorityType": "statute",
    "citation": "IRC §752",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1954-08-16",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/752",
    "ingestedAt": "2026-06-27T01:49:06.680Z",
    "text": "Under IRC §752, any increase in a partner’s share of partnership liabilities, or any increase in a partner’s individual liabilities because the partner assumes partnership liabilities, is treated as a contribution of money by that partner to the partnership. Any decrease in a partner’s share of partnership liabilities, or any decrease in a partner’s individual liabilities because the partnership assumes the partner’s individual liabilities, is treated as a distribution of money to the partner. A liability to which property is subject is treated, up to the property’s fair market value, as a liability of the property owner; on a sale or exchange of a partnership interest, liabilities are treated as liabilities would be in a sale or exchange of nonpartnership property.",
    "keywords": [
      "irc 752",
      "section 752",
      "partnership liabilities",
      "partner liabilities",
      "contribution of money",
      "distribution of money",
      "assumption of liabilities",
      "property subject to liability",
      "fair market value",
      "sale or exchange",
      "partnership interest",
      "outside basis"
    ]
  },
  {
    "chunkId": "ingested-irc-754",
    "authorityType": "statute",
    "citation": "IRC §754",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1954-08-16",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/754",
    "ingestedAt": "2026-06-27T01:49:24.461Z",
    "text": "If a partnership files an election under regulations prescribed by the Secretary, the basis of partnership property is adjusted for a property distribution as provided in section 734 and for a transfer of a partnership interest as provided in section 743. The election applies to all partnership property distributions and all transfers of partnership interests during the taxable year for which it is filed and all later taxable years. The partnership may revoke the election only subject to limitations provided by the Secretary’s regulations.",
    "keywords": [
      "irc §754",
      "section 754",
      "partnership election",
      "basis adjustment",
      "partnership property",
      "property distribution",
      "section 734",
      "partnership interest transfer",
      "section 743",
      "taxable year",
      "revocation",
      "secretary regulations"
    ]
  },
  {
    "chunkId": "ingested-irc-301",
    "authorityType": "statute",
    "citation": "IRC §301",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/301",
    "ingestedAt": "2026-06-27T01:52:49.182Z",
    "text": "Except as otherwise provided in chapter 1, a corporation’s distribution of property, as defined in section 317(a), to a shareholder with respect to its stock is taxed under section 301(c). The amount distributed is the money received plus the fair market value of other property received, valued on the distribution date, reduced but not below zero by specified liabilities assumed by the shareholder or attached to the property. The portion that is a dividend under section 316 is included in gross income; the nondividend portion reduces the shareholder’s adjusted stock basis, and any remaining nondividend excess over basis is treated as gain from the sale or exchange of property, except for the stated pre-March 1, 1913 increase-in-value exception. The basis of property received in the distribution is its fair market value.",
    "keywords": [
      "irc 301",
      "section 301",
      "distributions of property",
      "corporate distribution",
      "shareholder",
      "dividend",
      "section 316",
      "earnings and profits",
      "stock basis",
      "return of capital",
      "gain from sale",
      "fair market value",
      "liabilities",
      "section 317"
    ]
  },
  {
    "chunkId": "ingested-irc-311",
    "authorityType": "statute",
    "citation": "IRC §311",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1987-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/311",
    "ingestedAt": "2026-06-27T01:53:16.657Z",
    "text": "Except for the appreciated-property rule, a corporation recognizes no gain or loss on a distribution, not in complete liquidation, with respect to its stock of its own stock, rights to acquire its stock, or property. If a corporation distributes property other than its own obligation to a shareholder in a distribution to which subpart A applies, and the property’s fair market value exceeds its adjusted basis in the distributing corporation’s hands, the corporation recognizes gain as if it sold the property to the distributee at fair market value. Similar rules to section 336(b) apply for liabilities, and regulations may disregard certain losses in computing gain on distributions of partnership or trust interests.",
    "keywords": [
      "irc 311",
      "section 311",
      "corporate distributions",
      "appreciated property",
      "gain recognition",
      "loss disallowance",
      "fair market value",
      "adjusted basis",
      "shareholder distribution",
      "complete liquidation",
      "liabilities",
      "partnership interests",
      "trust interests"
    ]
  },
  {
    "chunkId": "ingested-irc-316",
    "authorityType": "statute",
    "citation": "IRC §316",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2011-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/316",
    "ingestedAt": "2026-06-27T01:53:50.267Z",
    "text": "For purposes of Subtitle A, a dividend is any distribution of property a corporation makes to its shareholders out of earnings and profits accumulated after February 28, 1913, or out of earnings and profits of the taxable year, computed at year-end without reduction for distributions made during that year. Except as otherwise provided, distributions are treated as made out of earnings and profits to the extent available, starting with the most recently accumulated earnings and profits. A distribution treated under Subchapter C as a section 301 distribution of property is treated as a distribution of property for this definition, while special rules apply for specified insurance company, personal holding company, regulated investment company, and real estate investment trust distributions.",
    "keywords": [
      "irc 316",
      "section 316",
      "dividend",
      "distribution of property",
      "corporation",
      "shareholders",
      "earnings and profits",
      "accumulated earnings",
      "current earnings",
      "section 301",
      "personal holding company",
      "regulated investment company",
      "real estate investment trust"
    ]
  },
  {
    "chunkId": "ingested-irc-351",
    "authorityType": "statute",
    "citation": "IRC §351",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/351",
    "ingestedAt": "2026-06-27T01:54:36.602Z",
    "text": "Under IRC §351, no gain or loss is recognized when one or more persons transfer property to a corporation solely in exchange for that corporation’s stock and, immediately after the exchange, the transferor or transferors are in control of the corporation as defined in §368(c). If the exchange otherwise qualifies but the recipient also receives money or other property, gain is recognized only up to the money received plus the fair market value of the other property, and no loss is recognized. Stock issued for services, certain transferee-corporation indebtedness, or accrued interest is not treated as issued for property, and §351 does not apply to transfers to an investment company or specified title 11 or similar-case debtor transfers.",
    "keywords": [
      "irc 351",
      "section 351",
      "transfer to corporation",
      "controlled corporation",
      "property transfer",
      "stock exchange",
      "nonrecognition",
      "control",
      "boot",
      "money received",
      "other property",
      "investment company",
      "services",
      "title 11"
    ]
  },
  {
    "chunkId": "ingested-irc-357",
    "authorityType": "statute",
    "citation": "IRC §357",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/357",
    "ingestedAt": "2026-06-27T01:55:05.846Z",
    "text": "Under IRC §357, when property that could be received tax-free under §351 or §361 is exchanged and another party assumes the taxpayer’s liability as part of the consideration, the liability assumption generally is not treated as money or other property and does not prevent §351 or §361 treatment. If the principal purpose of the liability assumption is Federal income tax avoidance, or the assumption lacks a bona fide business purpose, the full amount of the liability assumed is treated as money received by the taxpayer. For applicable §351 exchanges and specified §361 exchanges, if liabilities assumed exceed the total adjusted basis of the transferred property, the excess is recognized as gain, subject to the stated exceptions and exclusions for certain deductible or §736(a) liabilities.",
    "keywords": [
      "irc 357",
      "section 357",
      "assumption of liability",
      "section 351 exchange",
      "section 361 exchange",
      "boot",
      "tax avoidance",
      "bona fide business purpose",
      "liabilities exceed basis",
      "adjusted basis",
      "recognized gain",
      "recourse liability",
      "nonrecourse liability"
    ]
  },
  {
    "chunkId": "ingested-irc-1061",
    "authorityType": "statute",
    "citation": "IRC §1061",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2018-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1061",
    "ingestedAt": "2026-06-27T02:40:46.110Z",
    "text": "If a taxpayer holds one or more applicable partnership interests at any time during the taxable year, the taxpayer’s net long-term capital gain with respect to those interests is recomputed by substituting “3 years” for “1 year” in section 1222(3) and (4), and any excess of the originally computed net long-term capital gain over that recomputed amount is treated as short-term capital gain. Thus, gain with respect to an applicable partnership interest does not receive long-term capital gain treatment under this rule unless the relevant holding period is more than 3 years, notwithstanding section 83 or any section 83(b) election. An applicable partnership interest generally is a partnership interest transferred to or held by the taxpayer, directly or indirectly, in connection with substantial services by the taxpayer or a related person in an applicable trade or business, subject to the stated exclusions for certain corporate-held interests and qualifying capital interests.",
    "keywords": [
      "irc §1061",
      "section 1061",
      "carried interest",
      "applicable partnership interest",
      "three-year holding period",
      "long-term capital gain",
      "short-term capital gain",
      "section 1222",
      "section 83(b)",
      "partnership services",
      "applicable trade or business",
      "capital interest exception"
    ]
  },
  {
    "chunkId": "ingested-irc-1221",
    "authorityType": "statute",
    "citation": "IRC §1221",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2018-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1221",
    "ingestedAt": "2026-06-27T02:41:17.885Z",
    "text": "Under IRC §1221, a capital asset is property held by the taxpayer, whether or not connected with the taxpayer’s trade or business, except for the categories specifically excluded. Excluded property includes stock in trade, inventory-type property, property held primarily for sale to customers, depreciable trade-or-business property, real property used in a trade or business, specified creator-held intellectual or similar property, ordinary-course accounts or notes receivable, certain U.S. Government publications, and business supplies regularly used or consumed. Also excluded are commodities derivative financial instruments held by commodities derivatives dealers unless the statutory nondealer-connection and identification requirements are met, and hedging transactions clearly identified by the required time. A hedging transaction is one entered into in the normal course of the taxpayer’s trade or business primarily to manage specified price, currency, interest-rate, borrowing, obligation, or other prescribed risks.",
    "keywords": [
      "irc 1221",
      "section 1221",
      "capital asset",
      "inventory",
      "stock in trade",
      "customers",
      "depreciable property",
      "real property",
      "accounts receivable",
      "self-created property",
      "copyright",
      "hedging transaction",
      "commodities derivatives",
      "business supplies"
    ]
  },
  {
    "chunkId": "ingested-irc-1222",
    "authorityType": "statute",
    "citation": "IRC §1222",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2014-12-19",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1222",
    "ingestedAt": "2026-06-27T02:41:47.433Z",
    "text": "For §1222 purposes, gain or loss from the sale or exchange of a capital asset is short-term if the asset was held for not more than 1 year and long-term if held for more than 1 year, with gains counted to the extent included in gross income and losses to the extent included in taxable income. Net short-term capital gain or loss and net long-term capital gain or loss are determined by comparing gains and losses within the corresponding holding-period category for the taxable year. Capital gain net income is the excess of gains from sales or exchanges of capital assets over losses, while net capital loss is the excess of such losses over the amount allowed under §1211, with the stated corporate exclusion for short-term capital losses under §1212(a)(1). Net capital gain is the excess of net long-term capital gain for the taxable year over net short-term capital loss for that year.",
    "keywords": [
      "irc 1222",
      "section 1222",
      "capital gains",
      "capital losses",
      "short-term capital gain",
      "short-term capital loss",
      "long-term capital gain",
      "long-term capital loss",
      "holding period",
      "net capital gain",
      "net capital loss",
      "capital gain net income",
      "section 1211",
      "section 1212"
    ]
  },
  {
    "chunkId": "ingested-irc-1231",
    "authorityType": "statute",
    "citation": "IRC §1231",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2018-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1231",
    "ingestedAt": "2026-06-27T02:42:20.217Z",
    "text": "For any taxable year, net section 1231 treatment is determined by comparing section 1231 gains and section 1231 losses: if gains exceed losses, the gains and losses are treated as long-term capital gains and long-term capital losses; if gains do not exceed losses, they are not treated as gains and losses from sales or exchanges of capital assets. Section 1231 generally covers recognized gain or loss from sales, exchanges, or compulsory or involuntary conversions of property used in a trade or business, including qualifying depreciable property and real property held for more than 1 year, subject to the statutory exclusions and special rules. A net section 1231 gain is treated as ordinary income to the extent it does not exceed non-recaptured net section 1231 losses from the 5 most recent preceding taxable years.",
    "keywords": [
      "irc 1231",
      "section 1231",
      "trade or business property",
      "involuntary conversion",
      "long-term capital gain",
      "long-term capital loss",
      "ordinary income",
      "net section 1231 gain",
      "net section 1231 loss",
      "non-recaptured losses",
      "5-year lookback",
      "depreciable property",
      "real property"
    ]
  },
  {
    "chunkId": "ingested-irc-1245",
    "authorityType": "statute",
    "citation": "IRC §1245",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1245",
    "ingestedAt": "2026-06-27T02:43:27.392Z",
    "text": "When section 1245 property is disposed of, the ordinary-income amount is the excess of the lesser of the property’s recomputed basis or the amount realized in a sale, exchange, or involuntary conversion (or fair market value in any other disposition) over the property’s adjusted basis; this gain is recognized notwithstanding any other provision of the subtitle. Recomputed basis means adjusted basis increased by depreciation or amortization adjustments allowed or allowable, using the lesser amount actually allowed for a period if the taxpayer proves it by adequate records or other sufficient evidence. Section 1245 property includes depreciable personal property and specified depreciable or amortizable tangible property categories, and the rule does not apply to gifts or transfers at death except as provided for income in respect of a decedent; special limits apply for specified tax-free transfers, like-kind exchanges, involuntary conversions, partnership distributions, tax-exempt organization transfers, timber property, and amortizable section 197 intangibles.",
    "keywords": [
      "irc 1245",
      "section 1245",
      "depreciation recapture",
      "ordinary income",
      "recomputed basis",
      "adjusted basis",
      "amount realized",
      "fair market value",
      "section 1245 property",
      "depreciable property",
      "personal property",
      "amortization",
      "like-kind exchange",
      "involuntary conversion"
    ]
  },
  {
    "chunkId": "ingested-irc-1250",
    "authorityType": "statute",
    "citation": "IRC §1250",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1964-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1250",
    "ingestedAt": "2026-06-27T02:43:56.495Z",
    "text": "On a disposition of section 1250 property, gain is treated as ordinary income to the extent of the applicable percentage of the lower of the property’s additional depreciation or the excess of amount realized, or fair market value for other dispositions, over adjusted basis; this ordinary-income treatment applies notwithstanding other provisions. Section 1250 property is depreciable real property other than section 1245 property. For property held more than one year, “additional depreciation” generally means depreciation adjustments only to the extent they exceed the depreciation that would have resulted under the straight-line method, so straight-line depreciation alone does not create ordinary income recapture under this section. The section does not apply to gifts or transfers at death, and special limitations apply to certain carryover-basis transfers, like-kind exchanges, involuntary conversions, partnership distributions, and transfers involving tax-exempt organizations.",
    "keywords": [
      "irc 1250",
      "section 1250",
      "depreciable realty",
      "section 1250 property",
      "ordinary income",
      "additional depreciation",
      "straight-line depreciation",
      "depreciation recapture",
      "adjusted basis",
      "amount realized",
      "fair market value",
      "gifts",
      "transfers at death",
      "like-kind exchanges",
      "involuntary conversions"
    ]
  },
  {
    "chunkId": "ingested-irc-1014",
    "authorityType": "statute",
    "citation": "IRC §1014",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1954-08-16",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1014",
    "ingestedAt": "2026-06-27T02:44:46.517Z",
    "text": "Except as otherwise provided in IRC §1014, a person who acquires property from a decedent, or to whom property passes from a decedent, takes a basis equal to the property’s fair market value on the date of the decedent’s death, provided the person did not sell, exchange, or otherwise dispose of the property before death. If an election under §2032 is made, basis is the value at the applicable valuation date under that section; if an election under §2032A is made, basis is the value determined under that section. This stepped-up or stepped-down basis rule does not apply to property that is a right to receive income in respect of a decedent under §691.",
    "keywords": [
      "irc 1014",
      "section 1014",
      "basis",
      "decedent",
      "fair market value",
      "date of death",
      "stepped-up basis",
      "stepped-down basis",
      "alternate valuation date",
      "section 2032",
      "section 2032a",
      "income in respect of a decedent",
      "section 691",
      "inheritance",
      "bequest"
    ]
  },
  {
    "chunkId": "ingested-irc-1015",
    "authorityType": "statute",
    "citation": "IRC §1015",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1977-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1015",
    "ingestedAt": "2026-06-27T02:45:14.555Z",
    "text": "For property acquired by gift after December 31, 1920, the donee’s basis generally is the same as it would be in the donor’s hands, or in the hands of the last prior owner who did not acquire it by gift, adjusted under section 1016 before the gift. If that carryover basis exceeds the property’s fair market value at the time of the gift, the basis for determining a loss is the fair market value at the time of the gift. For gifts made after December 31, 1976, any basis increase for gift tax paid is limited to an amount, not exceeding the tax paid, based on the ratio of the gift’s net appreciation to the amount of the gift; net appreciation is the excess of fair market value over the donor’s adjusted basis immediately before the gift.",
    "keywords": [
      "1015",
      "gift basis",
      "carryover basis",
      "donee",
      "donor basis",
      "fair market value",
      "loss basis",
      "dual basis",
      "gift tax paid",
      "net appreciation",
      "adjusted basis",
      "section 1016"
    ]
  },
  {
    "chunkId": "ingested-irc-1041",
    "authorityType": "statute",
    "citation": "IRC §1041",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1988-06-22",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1041",
    "ingestedAt": "2026-06-27T03:12:54.779Z",
    "text": "No gain or loss is recognized on a transfer of property from an individual to, or in trust for the benefit of, a spouse, or a former spouse if the transfer is incident to divorce. The transferee is treated as acquiring the property by gift and takes the transferor’s adjusted basis, so the transfer is nonrecognition with carryover basis rather than a basis step-up. A transfer is incident to divorce if it occurs within 1 year after the marriage ceases or is related to the cessation of the marriage. This nonrecognition rule does not apply if the transferee spouse or former spouse is a nonresident alien, or to a trust transfer to the extent liabilities assumed plus liabilities to which the property is subject exceed the total adjusted basis of the transferred property.",
    "keywords": [
      "irc §1041",
      "1041",
      "spousal transfers",
      "divorce",
      "incident to divorce",
      "nonrecognition",
      "carryover basis",
      "gift treatment",
      "former spouse",
      "property transfer",
      "nonresident alien",
      "trust liabilities",
      "adjusted basis"
    ]
  },
  {
    "chunkId": "ingested-irc-280a",
    "authorityType": "statute",
    "citation": "IRC §280A",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1999-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/280A",
    "ingestedAt": "2026-06-27T03:13:26.410Z",
    "text": "For an individual or S corporation, IRC §280A generally disallows deductions for use of a dwelling unit used by the taxpayer during the taxable year as a residence, except for deductions allowable without regard to business or income-producing use. The disallowance does not apply to expenses allocable to a portion used exclusively and regularly as the taxpayer’s principal place of business, to meet or deal with patients, clients, or customers in the normal course of business, or in a separate unattached structure used in the taxpayer’s trade or business; for employees, the exclusive use must be for the employer’s convenience. Deductions for qualifying business, storage, day-care, or residential rental use are limited to gross income from that use reduced by specified otherwise allowable and related deductions, and any disallowed amount is carried to the succeeding taxable year subject to the same limitation. If a dwelling unit used as a residence is actually rented for less than 15 days during the taxable year, rental deductions are not allowed and the rental income is excluded from gross income.",
    "keywords": [
      "irc 280a",
      "home office",
      "business use of home",
      "dwelling unit",
      "used as residence",
      "exclusive use",
      "regular basis",
      "principal place of business",
      "clients customers",
      "gross income limitation",
      "carryforward",
      "rental less than 15 days",
      "rental income exclusion"
    ]
  },
  {
    "chunkId": "ingested-irc-166",
    "authorityType": "statute",
    "citation": "IRC §166",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "1987-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/166",
    "ingestedAt": "2026-06-27T03:13:55.591Z",
    "text": "A taxpayer may deduct a debt that becomes wholly worthless during the taxable year, and the Secretary may allow a deduction for a partially worthless debt to the extent the debt is charged off during the taxable year and is recoverable only in part. The deductible amount is determined using the debt’s adjusted basis under section 1011. For a taxpayer other than a corporation, a nonbusiness debt is not deductible under the general bad-debt rule; if it becomes worthless during the taxable year, the resulting loss is treated as a loss from the sale or exchange of a capital asset held for not more than 1 year. A nonbusiness debt is any debt other than one created or acquired in connection with the taxpayer’s trade or business or one whose worthlessness loss is incurred in that trade or business, and section 166 does not apply to a debt evidenced by a security described in section 165(g)(2)(C).",
    "keywords": [
      "166",
      "bad debt",
      "worthless debt",
      "partially worthless",
      "charged off",
      "adjusted basis",
      "section 1011",
      "nonbusiness debt",
      "trade or business",
      "capital asset",
      "short-term capital loss",
      "section 165(g)(2)(c)"
    ]
  },
  {
    "chunkId": "ingested-irc-318",
    "authorityType": "statute",
    "citation": "IRC §318",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/318",
    "ingestedAt": "2026-06-27T03:14:25.025Z",
    "text": "For provisions of Subchapter C that expressly apply IRC §318, a person is treated as owning stock owned directly or indirectly by specified family members, including a spouse unless legally separated, children, grandchildren, parents, and legally adopted children treated as children by blood. Stock is attributed proportionately between partnerships, estates, trusts, corporations, and their owners or beneficiaries under the stated rules, including corporate attribution when a person owns 50 percent or more in value of the corporation and a trust remote contingent interest exception at 5 percent or less. A person with an option to acquire stock is treated as owning that stock, including options to acquire options; constructive ownership generally is treated as actual ownership for further attribution, subject to the stated limits on repeated family attribution and sidewise entity attribution, and S corporations are treated as partnerships for these attribution rules except in determining ownership of S corporation stock itself.",
    "keywords": [
      "irc 318",
      "constructive ownership",
      "stock attribution",
      "family attribution",
      "spouse",
      "children",
      "partnerships",
      "estates",
      "trusts",
      "corporations",
      "50 percent",
      "options",
      "s corporation",
      "remote contingent interest"
    ]
  },
  {
    "chunkId": "ingested-irc-469",
    "authorityType": "statute",
    "citation": "IRC §469",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025,
      2026
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/469",
    "ingestedAt": "2026-06-27T03:15:05.306Z",
    "text": "For an individual, estate, trust, closely held C corporation, or personal service corporation, a passive activity loss or passive activity credit for the taxable year is not allowed except as provided in §469. A passive activity is a trade or business in which the taxpayer does not materially participate—meaning involvement is not regular, continuous, and substantial—and, except for the special rental real estate rules, any rental activity is also passive. A disallowed loss or credit is treated as a deduction or credit allocable to the same activity in the next taxable year; for a former passive activity, unused amounts first offset income or tax liability from that activity and the remainder continues as passive. If the taxpayer disposes of the entire interest in a passive or former passive activity in a fully taxable transaction, the excess loss from that activity over net income or gain from all other passive activities is treated as a loss that is not from a passive activity, subject to the section’s special disposition rules.",
    "keywords": [
      "irc 469",
      "passive activity loss",
      "passive activity credit",
      "material participation",
      "rental activity",
      "carryforward",
      "suspended losses",
      "fully taxable disposition",
      "closely held c corporation",
      "personal service corporation",
      "real property business",
      "former passive activity"
    ]
  }
];
