// AUTO-GENERATED by scripts/ingest-authority.mts — re-run to refresh; do not hand-edit.
// Grounded primary-authority chunks: each is a concise operative-rule paraphrase produced
// FROM the fetched source text, and every $/%/year figure was verified to appear in that
// source before admission. Public domain (statute) — §7216-clean. Registered in authority/store.ts.
import type { AuthorityChunk } from "../tax/authority/store";

export const CORPUS_INGESTED: AuthorityChunk[] = [
  {
    "chunkId": "ingested-irc-3121",
    "authorityType": "statute",
    "citation": "IRC §3121",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/3121",
    "ingestedAt": "2026-06-24T09:19:16.876Z",
    "text": "Under IRC §3121(a), 'wages' for FICA purposes means all remuneration for employment, including the cash value of remuneration paid in any medium other than cash, subject to enumerated exclusions. Cash tips received by an employee in any calendar month are included in wages—and therefore subject to employer and employee FICA taxes under Chapter 21—unless the amount of such cash tips in that month is less than $20; tips paid in any medium other than cash are excluded from wages entirely. Because tips meeting the $20-per-month threshold are FICA wages processed through the employer's payroll, they are not subject to self-employment tax. The Social Security wage base cap applies to the taxes imposed under §§3101(a) and 3111(a) once remuneration paid by a single employer equals the contribution and benefit base determined under §230 of the Social Security Act for that calendar year.",
    "keywords": [
      "irc 3121",
      "fica wages",
      "tips as wages",
      "cash tips",
      "twenty dollar tip threshold",
      "employment definition",
      "payroll fica",
      "self-employment tax exclusion",
      "contribution and benefit base",
      "social security wage base",
      "remuneration",
      "chapter 21",
      "tip income",
      "employer fica",
      "employee fica"
    ]
  },
  {
    "chunkId": "ingested-irc-1402",
    "authorityType": "statute",
    "citation": "IRC §1402",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1402",
    "ingestedAt": "2026-06-24T09:19:26.191Z",
    "text": "Under IRC §1402, 'net earnings from self-employment' means gross income from a trade or business carried on by an individual, less allowable deductions attributable to that trade or business, plus the individual's distributive share of ordinary income or loss from a partnership trade or business. Certain items are excluded from this base, including real estate rentals (unless received as a dealer), dividends and interest (unless received by a dealer in stocks or securities), capital gains and losses, and a limited partner's distributive share of partnership income other than guaranteed payments for services actually rendered. The term 'self-employment income' (the SE-tax base) does not include net earnings below $400, and for the OASDI portion under §1401(a) it is capped by reducing the contribution and benefit base (as determined under §230 of the Social Security Act) by wages already paid to the individual during the taxable year. W-2 wages and tips received as an employee are thus excluded from the SE-tax base because employee service is expressly carved out of the definition of 'trade or business' for self-employment purposes.",
    "keywords": [
      "irc 1402",
      "net earnings from self-employment",
      "self-employment income",
      "se tax base",
      "trade or business",
      "limited partner exclusion",
      "guaranteed payments",
      "contribution and benefit base",
      "wages offset",
      "real estate rental exclusion",
      "capital gain exclusion",
      "partnership distributive share",
      "400 dollar threshold",
      "employee exclusion",
      "self-employment tax"
    ]
  },
  {
    "chunkId": "ingested-irc-1401",
    "authorityType": "statute",
    "citation": "IRC §1401",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2013-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/1401",
    "ingestedAt": "2026-06-24T09:19:35.051Z",
    "text": "Under IRC §1401, self-employment income is subject to two separate taxes each taxable year: (1) an OASDI (old-age, survivors, and disability insurance) tax of 12.4 percent of self-employment income, and (2) a hospital insurance (Medicare) tax of 2.9 percent of self-employment income. In addition, for taxable years beginning after December 31, 2012, an additional 0.9 percent Medicare tax applies to self-employment income exceeding $250,000 for joint filers, $200,000 for single and other filers, or one-half of the joint-return threshold for married filing separately. The $250,000 and $200,000 thresholds are each reduced (but not below zero) by wages already taken into account for the additional Medicare tax under section 3121(b)(2). Self-employment income covered exclusively by a foreign country's social security system under an agreement authorized by section 233 of the Social Security Act is exempt from these taxes.",
    "keywords": [
      "irc section 1401",
      "self-employment tax",
      "oasdi",
      "social security tax",
      "medicare tax",
      "hospital insurance",
      "12.4 percent",
      "2.9 percent",
      "0.9 percent additional medicare tax",
      "self-employment income",
      "net investment income",
      "high-income threshold",
      "totalization agreement",
      "chapter 2 tax"
    ]
  },
  {
    "chunkId": "ingested-irc-61",
    "authorityType": "statute",
    "citation": "IRC §61",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2019-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/61",
    "ingestedAt": "2026-06-24T09:19:51.903Z",
    "text": "Under IRC §61(a), gross income means all income from whatever source derived, except as otherwise provided in Subtitle A of the Code. The definition is broad and inclusive, encompassing (but not limited to) compensation for services (including fees, commissions, and fringe benefits), gross income from business, gains from dealings in property, interest, rents, royalties, dividends, annuities, income from life insurance and endowment contracts, pensions, income from discharge of indebtedness, a distributive share of partnership gross income, income in respect of a decedent, and income from an interest in an estate or trust. Items specifically included in gross income are addressed in Part II (§71 and following), while items specifically excluded are addressed in Part III (§101 and following). A tax preparer should presume any accession to wealth is gross income unless a specific statutory exclusion applies.",
    "keywords": [
      "irc §61",
      "gross income defined",
      "all income from whatever source derived",
      "compensation for services",
      "fringe benefits",
      "discharge of indebtedness",
      "distributive share partnership",
      "income in respect of a decedent",
      "dividends interest rents royalties",
      "exclusions from gross income",
      "inclusions in gross income",
      "annuities pensions",
      "gains from property dealings",
      "subtitle a chapter 1"
    ]
  },
  {
    "chunkId": "ingested-irc-62",
    "authorityType": "statute",
    "citation": "IRC §62",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/62",
    "ingestedAt": "2026-06-24T09:20:03.663Z",
    "text": "Under IRC §62, an individual's adjusted gross income (AGI) equals gross income reduced by specific 'above-the-line' deductions taken before any standard or itemized deduction. Allowable above-the-line deductions include: trade or business expenses (other than employee services), reimbursed employee business expenses under a qualifying arrangement, certain performing-artist and state/local-official expenses, eligible-educator classroom expenses (up to $250, inflation-adjusted for years after 2015 in $50 increments), Armed Forces reservist travel expenses for assignments more than 100 miles from home, losses from property sales, rental and royalty expenses, depreciation for life tenants and trust income beneficiaries, self-employed retirement plan contributions (§404), IRA deductions (§219), early-withdrawal penalties on time deposits, reforestation expenses (§194), jury-duty pay remitted to an employer, moving expenses (§217), Archer MSA deductions (§220), education-loan interest (§221), health savings account deductions (§223), attorney fees and court costs in unlawful-discrimination or whistleblower-award actions (capped at the gross income inclusion from the judgment or award), and supplemental unemployment compensation repayments. The §199A deduction is explicitly excluded from all of the above categories, and no item may be deducted more than once.",
    "keywords": [
      "irc §62",
      "adjusted gross income",
      "above-the-line deductions",
      "eligible educator",
      "performing artist",
      "self-employed retirement",
      "health savings account",
      "education loan interest",
      "archer msa",
      "reimbursed employee expenses",
      "whistleblower attorney fees",
      "reservist travel expenses",
      "jury duty pay",
      "inflation adjustment"
    ]
  },
  {
    "chunkId": "ingested-irc-213",
    "authorityType": "statute",
    "citation": "IRC §213",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2021-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/213",
    "ingestedAt": "2026-06-24T09:20:12.911Z",
    "text": "A taxpayer may deduct unreimbursed expenses paid during the taxable year for medical care of the taxpayer, spouse, or qualifying dependent, but only to the extent those expenses exceed 7.5 percent of adjusted gross income. 'Medical care' covers amounts paid for diagnosis, cure, mitigation, treatment, or prevention of disease; transportation essential to such care; qualified long-term care services; and qualifying insurance premiums—but expressly excludes cosmetic surgery unless required to correct a congenital abnormality, accident-related injury, or disfiguring disease. For medicine and drugs, only prescribed drugs and insulin qualify. Lodging away from home while receiving medical care from a physician in a licensed hospital may be included, but the deductible lodging amount is capped at $50 per night per individual. Any expense already allowed as a credit under IRC §21 may not also be deducted as a medical expense.",
    "keywords": [
      "irc 213",
      "medical expense deduction",
      "7.5 percent agi floor",
      "adjusted gross income threshold",
      "unreimbursed medical expenses",
      "prescribed drugs",
      "qualified long-term care",
      "cosmetic surgery exclusion",
      "lodging medical care",
      "medical care definition",
      "insulin",
      "dependent medical expenses",
      "insurance premiums medical care",
      "schedule a itemized deduction"
    ]
  },
  {
    "chunkId": "ingested-irc-223",
    "authorityType": "statute",
    "citation": "IRC §223",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/223",
    "ingestedAt": "2026-06-24T09:20:23.946Z",
    "text": "An eligible individual covered by a high deductible health plan (HDHP) on the first day of a month may deduct cash contributions made to a health savings account (HSA), limited to 1/12 of $2,250 (self-only coverage) or $4,500 (family coverage) for each month of eligibility; an individual who has attained age 55 before the close of the taxable year may contribute an additional amount up to $1,000 per year (as phased in by the statute's table). An HDHP must have an annual deductible of at least $1,000 for self-only coverage (twice that for family coverage) and total annual out-of-pocket expenses not exceeding $5,000 for self-only coverage (twice that for family coverage). The annual limit is reduced dollar-for-dollar by Archer MSA contributions, employer contributions excludable under §106(d), and IRA-to-HSA rollovers under §408(d)(9); a dependent who may be claimed on another taxpayer's return is ineligible for the deduction, and the limit drops to zero for any month the individual is enrolled in Medicare. Distributions used exclusively for qualified medical expenses are excluded from gross income, while non-qualifying distributions are included in gross income and subject to an additional 20-percent tax, with exceptions for death or disability.",
    "keywords": [
      "irc §223",
      "health savings account",
      "hsa deduction",
      "high deductible health plan",
      "hdhp",
      "eligible individual",
      "contribution limit",
      "self-only coverage",
      "family coverage",
      "catch-up contribution",
      "age 55",
      "qualified medical expenses",
      "archer msa coordination",
      "medicare ineligibility",
      "20 percent additional tax"
    ]
  },
  {
    "chunkId": "ingested-irc-219",
    "authorityType": "statute",
    "citation": "IRC §219",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/219",
    "ingestedAt": "2026-06-24T09:20:37.845Z",
    "text": "Under IRC §219, an individual may deduct qualified retirement contributions (cash amounts paid to an individual retirement plan) for the taxable year, limited to the lesser of (a) the deductible amount—a base dollar figure of $5,000 indexed for cost-of-living after 2008 in $500 increments—or (b) the individual's compensation includible in gross income for the year. Individuals who have attained age 50 before the close of the taxable year may increase the deductible amount by $1,000 (itself indexed for cost-of-living after 2023 in $100 increments). A non-working or lower-earning spouse filing jointly may use the higher-earning spouse's compensation to determine the deductible amount under the Kay Bailey Hutchison Spousal IRA rules. If the individual (or their spouse) is an active participant in an employer-sponsored retirement plan for any part of a plan year ending within the taxable year, the deductible amount is phased out ratably over a $10,000 AGI range ($20,000 for joint filers) above an applicable dollar threshold—$80,000 for joint filers, $50,000 for single filers, and zero for married filing separately—each threshold indexed in $1,000 increments after 2006; a non-active-participant spouse of an active participant has a separate, higher applicable dollar amount of $150,000 phased out over $10,000.",
    "keywords": [
      "irc 219",
      "deductible ira contribution",
      "qualified retirement contribution",
      "individual retirement plan",
      "catch-up contribution",
      "active participant",
      "phase-out",
      "spousal ira",
      "kay bailey hutchison",
      "applicable dollar amount",
      "cost-of-living adjustment",
      "compensation",
      "adjusted gross income",
      "traditional ira deduction",
      "retirement savings"
    ]
  },
  {
    "chunkId": "ingested-irc-163",
    "authorityType": "statute",
    "citation": "IRC §163",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2018-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/163",
    "ingestedAt": "2026-06-24T09:20:45.745Z",
    "text": "Under IRC §163(a), all interest paid or accrued within the taxable year on indebtedness is generally deductible. For individual taxpayers, 'personal interest' is disallowed, but 'qualified residence interest' is excepted and remains deductible; qualified residence interest includes interest on acquisition indebtedness (debt incurred to acquire, construct, or substantially improve a qualified residence and secured by it) up to a $1,000,000 aggregate limit ($500,000 for married filing separately) for indebtedness incurred on or before December 15, 2017, and up to $750,000 ($375,000 for married filing separately) for indebtedness incurred after December 15, 2017, with home equity indebtedness interest disallowed for taxable years beginning after December 31, 2017. Investment interest deductions for non-corporate taxpayers are limited to net investment income for the taxable year, with any disallowed amount carried forward to the succeeding taxable year.",
    "keywords": [
      "irc §163",
      "interest deduction",
      "qualified residence interest",
      "acquisition indebtedness",
      "home equity indebtedness",
      "mortgage interest",
      "personal interest disallowance",
      "investment interest limitation",
      "net investment income",
      "750000 limit",
      "1000000 limit",
      "married filing separately",
      "carryforward disallowed interest",
      "taxable year 2024 2025"
    ]
  },
  {
    "chunkId": "ingested-irc-6662",
    "authorityType": "statute",
    "citation": "IRC §6662",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2024-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/6662",
    "ingestedAt": "2026-06-24T09:20:57.774Z",
    "text": "Under IRC §6662, a 20% accuracy-related penalty is added to the tax on any portion of an underpayment attributable to negligence or disregard of rules, a substantial understatement of income tax, a substantial valuation misstatement, a substantial overstatement of pension liabilities, a substantial estate or gift tax valuation understatement, a transaction lacking economic substance, an undisclosed foreign financial asset understatement, an inconsistent estate basis, an overstatement of the section 170(p) deduction, or a disallowance under section 170(h)(7). A substantial understatement of income tax exists when the understatement exceeds the greater of 10% of the tax required to be shown on the return or $5,000 (for corporations other than S corporations or personal holding companies, the threshold is the lesser of 10% of tax required or $10,000, but at least $10,000, capped at $10,000,000; for taxpayers claiming a section 199A deduction, the 10% threshold is reduced to 5%). The penalty rate is increased to 40% for gross valuation misstatements, nondisclosed noneconomic substance transactions, and undisclosed foreign financial asset understatements, and to 50% for overstatements of the section 170(p) deduction. The understatement amount is reduced for positions supported by substantial authority or adequately disclosed items with a reasonable basis, but this reduction does not apply to tax shelter items. No §6662 penalty applies to any portion of an underpayment already subject to the fraud penalty under §6663 or, generally, to reportable transaction understatements subject to §6662A.",
    "keywords": [
      "irc 6662",
      "accuracy-related penalty",
      "underpayment",
      "substantial understatement",
      "negligence",
      "valuation misstatement",
      "20 percent penalty",
      "40 percent penalty",
      "tax shelter",
      "substantial authority",
      "section 199a",
      "economic substance",
      "foreign financial asset",
      "gross valuation misstatement",
      "income tax understatement threshold"
    ]
  },
  {
    "chunkId": "ingested-irc-6651",
    "authorityType": "statute",
    "citation": "IRC §6651",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2020-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/6651",
    "ingestedAt": "2026-06-24T09:21:08.702Z",
    "text": "Under IRC §6651, a taxpayer who fails to file a required return by the prescribed due date (including extensions) is subject to an addition to tax of 5 percent of the net tax due for each month or fraction thereof the return is late, up to a maximum of 25 percent; if the failure is fraudulent, the rate rises to 15 percent per month with a 75 percent cap. A separate failure-to-pay penalty of 0.5 percent per month (maximum 25 percent) applies to unpaid tax shown on a return, reduced to 0.25 percent per month during any month an installment agreement under §6159 is in effect; that rate increases to 1 percent per month after IRS issues a levy notice under §6331(d) or demands immediate payment under §6331(a). When both failure-to-file and failure-to-pay penalties apply in the same month, the failure-to-file addition is reduced by the failure-to-pay amount for that month. For chapter 1 income tax returns filed more than 60 days late, the failure-to-file penalty is at least the lesser of $435 (subject to cost-of-living adjustment for returns required to be filed in calendar years after 2020) or 100 percent of the tax required to be shown, unless the failure is due to reasonable cause and not willful neglect; these penalties do not apply to failures to pay estimated tax.",
    "keywords": [
      "irc 6651",
      "failure to file penalty",
      "failure to pay penalty",
      "5 percent per month",
      "0.5 percent per month",
      "25 percent maximum",
      "reasonable cause",
      "willful neglect",
      "installment agreement reduction",
      "fraudulent failure to file",
      "minimum penalty",
      "cost-of-living adjustment",
      "levy notice",
      "estimated tax exception",
      "net amount due"
    ]
  },
  {
    "chunkId": "ingested-irc-6694",
    "authorityType": "statute",
    "citation": "IRC §6694",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "2016-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/6694",
    "ingestedAt": "2026-06-24T09:21:18.524Z",
    "text": "A tax return preparer who prepares a return or refund claim containing an understatement of liability due to an unreasonable position (one lacking substantial authority, or lacking a reasonable basis if disclosed, or failing the more-likely-than-not standard for tax shelters and section 6662A reportable transactions) and who knew or should have known of that position must pay a penalty equal to the greater of $1,000 or 50 percent of the income derived from that return or claim, unless reasonable cause and good faith are shown. If the understatement results from willful or reckless conduct—including a willful attempt to understate tax or reckless/intentional disregard of rules—the penalty rises to the greater of $5,000 or 75 percent of the income derived, reduced by any amount already paid under the unreasonable-position penalty. A preparer may suspend collection of the full penalty by paying at least 15 percent within 30 days of notice and demand and filing a refund claim, then timely bringing suit in U.S. district court. If a final administrative or judicial determination establishes there was no understatement, any assessed penalty is abated and amounts paid are refunded.",
    "keywords": [
      "irc 6694",
      "section 6694",
      "tax return preparer",
      "understatement penalty",
      "unreasonable position",
      "substantial authority",
      "willful reckless conduct",
      "preparer penalty",
      "reasonable cause good faith",
      "tax shelter reportable transaction",
      "more likely than not",
      "reasonable basis",
      "disclosed position",
      "understatement of liability",
      "6662a"
    ]
  },
  {
    "chunkId": "ingested-irc-7216",
    "authorityType": "statute",
    "citation": "IRC §7216",
    "jurisdiction": "federal",
    "taxYear": [
      2024,
      2025
    ],
    "effectiveDate": "1989-01-01",
    "sourceUrl": "https://www.law.cornell.edu/uscode/text/26/7216",
    "ingestedAt": "2026-06-24T09:21:24.666Z",
    "text": "Under IRC §7216, any person engaged in the business of preparing income tax returns under chapter 1, or who prepares such returns for compensation, commits a misdemeanor if they knowingly or recklessly disclose or use for any unauthorized purpose information furnished in connection with return preparation. Upon conviction, the penalty is a fine of not more than $1,000—or not more than $100,000 where section 6713(b) applies—or imprisonment of not more than 1 year, or both, plus costs of prosecution. Exceptions exist for disclosures required by other provisions of the Code or court order, use of information to prepare state/local tax returns for the same taxpayer, and disclosures or uses permitted by Treasury regulations (including quality or peer reviews).",
    "keywords": [
      "irc §7216",
      "section 7216",
      "tax preparer",
      "return information",
      "disclosure",
      "unauthorized use",
      "misdemeanor",
      "criminal penalty",
      "fine",
      "imprisonment",
      "chapter 1 returns",
      "section 6713(b)",
      "peer review",
      "confidentiality",
      "return preparation"
    ]
  }
];
