// L1 authority ingestion pipeline (durable, re-runnable). For each target section it:
//   1. FETCHES the real primary-source text (keyless: LII for IRC, eCFR XML for 26 CFR),
//   2. has Claude write a CONCISE operative-rule AuthorityChunk *from that text* (not memory),
//   3. GROUNDING GATE: every $/%/year figure in the chunk must appear in the source — else reject,
//   4. writes the survivors to lib/research/corpus-ingested.ts (registered alongside the others).
// PUBLIC authority only (no taxpayer data → §7216-clean). Run:
//   node --env-file=.env.local --import tsx scripts/ingest-authority.mts [--write] [section...]
import { getProvider } from "../lib/ai/provider-factory";
import type { AIProvider } from "../lib/ai/provider";
import { authorityChunkSchema, type AuthorityChunk } from "../lib/tax/authority/store";

// ── Targets: Phase-1 federal scope (1040 + the 4 due-diligence credits + gap-closers). Each entry
// is a real, resolvable primary source. taxYear lists the years the rule (as fetched) governs. ──
type Target = { cite: string; url: string; type: AuthorityChunk["authorityType"]; taxYear: number[]; note: string; delegationBasis?: AuthorityChunk["delegationBasis"]; anchor?: string };
const lii = (n: string) => `https://www.law.cornell.edu/uscode/text/26/${n}`;
// LII also hosts the Treasury Regulations (CFR Title 26) in the same clean format — reuse the pipeline.
const cfr = (n: string) => `https://www.law.cornell.edu/cfr/text/26/${n}`;
const TARGETS: Target[] = [
  { cite: "IRC §3121", url: lii("3121"), type: "statute", taxYear: [2024, 2025, 2026], note: "FICA DEFINITIONS — 'wages' means all remuneration for employment, including cash tips of $20 or more a month, with enumerated EXCLUSIONS (e.g., amounts above the Social Security wage base for OASDI, certain fringe benefits, employer plan contributions); 'employment' is service performed by an employee for an employer; tips are wages (so they run through payroll FICA, not SE tax)" },
  { cite: "IRC §1402", url: lii("1402"), type: "statute", taxYear: [2024, 2025], note: "net earnings from self-employment — defines the SE-tax base (excludes W-2 wages/tips)" },
  { cite: "IRC §1401", url: lii("1401"), type: "statute", taxYear: [2024, 2025], note: "self-employment tax rate (OASDI + Medicare portions)" },
  { cite: "IRC §1411", url: lii("1411"), type: "statute", taxYear: [2024, 2025], note: "3.8% net investment income tax + MAGI thresholds" },
  { cite: "IRC §61", url: lii("61"), type: "statute", taxYear: [2024, 2025], note: "gross income defined — all income from whatever source derived" },
  { cite: "IRC §62", url: lii("62"), type: "statute", taxYear: [2024, 2025], note: "adjusted gross income — the above-the-line deductions" },
  { cite: "IRC §213", url: lii("213"), type: "statute", taxYear: [2024, 2025], note: "medical-expense deduction + the AGI floor" },
  { cite: "IRC §223", url: lii("223"), type: "statute", taxYear: [2024, 2025], note: "HSA deduction + contribution limits / HDHP definition" },
  { cite: "IRC §219", url: lii("219"), type: "statute", taxYear: [2024, 2025], note: "deductible IRA contributions" },
  { cite: "IRC §163", url: lii("163"), type: "statute", taxYear: [2024, 2025, 2026], note: "INTEREST DEDUCTION — the §163(h) qualified-residence (home-mortgage) interest rules: acquisition indebtedness is capped at $750,000 ($375,000 MFS) for debt incurred AFTER December 15, 2017, but debt incurred ON OR BEFORE December 15, 2017 keeps the grandfathered $1,000,000 ($500,000 MFS) limit; personal interest is otherwise nondeductible. The §163(j) business-interest limitation caps the deduction at business interest income plus 30% of adjusted taxable income (ATI), with a small-business exception" },
  { cite: "IRC §6662", url: lii("6662"), type: "statute", taxYear: [2024, 2025], note: "accuracy-related penalty (20%) + substantial understatement" },
  { cite: "IRC §6651", url: lii("6651"), type: "statute", taxYear: [2024, 2025], note: "failure-to-file and failure-to-pay penalties" },
  { cite: "IRC §6694", url: lii("6694"), type: "statute", taxYear: [2024, 2025], note: "tax-return-preparer understatement penalty" },
  { cite: "IRC §7216", url: lii("7216"), type: "statute", taxYear: [2024, 2025], note: "criminal penalty for preparer disclosure/use of return information" },
  // Gap-closers from the round-3 held-out diagnostic (OBBBA-era). Each is fetched from the current
  // USC text and figure-grounded; DRY-RUN + verify the figures reflect post-OBBBA law before --write.
  { cite: "IRC §30D", url: lii("30D"), type: "statute", taxYear: [2025, 2026], note: "clean vehicle credit — OBBBA terminates it for vehicles acquired after Sept 30, 2025" },
  { cite: "IRC §25D", url: lii("25D"), type: "statute", taxYear: [2025, 2026], note: "residential clean energy credit — OBBBA ends it for expenditures after Dec 31, 2025 (installation-completion keyed)" },
  { cite: "IRC §6050W", url: lii("6050W"), type: "statute", taxYear: [2025, 2026], note: "1099-K / third-party settlement reporting — OBBBA restores the $20,000-and-200-transaction threshold" },
  { cite: "IRC §174A", url: lii("174A"), type: "statute", taxYear: [2025, 2026], note: "domestic R&D — OBBBA restores current expensing for tax years beginning after Dec 31, 2024" },
  // ── ENTITY LAW — Subchapter S CORE (the audit's #1 binding constraint: ~half an EA practice, 0% covered).
  // The most common business return. Stable, non-OBBBA provisions, so taxYear spans current years. Each is
  // fetched from current USC text and figure-grounded; capture the operative RULE, not a worked example. ──
  { cite: "IRC §1361", url: lii("1361"), type: "statute", taxYear: [2024, 2025, 2026], note: "S corporation defined — small business corporation: a domestic corporation with no more than 100 shareholders, only eligible shareholders (individuals, estates, certain trusts and exempt orgs — NOT nonresident aliens, partnerships, or C corporations), and only ONE class of stock (differences in voting rights are allowed)" },
  { cite: "IRC §1366", url: lii("1366"), type: "statute", taxYear: [2024, 2025, 2026], note: "pass-through to shareholders — each shareholder takes into account a pro-rata share of the S corporation's separately stated items and nonseparately computed income/loss; the aggregate loss/deduction a shareholder may take is LIMITED to the shareholder's adjusted basis in stock plus basis in any indebtedness of the S corp to the shareholder, with disallowed losses carried forward" },
  { cite: "IRC §1367", url: lii("1367"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis adjustments — a shareholder's stock basis is INCREASED by income items (separately stated income and tax-exempt income) and DECREASED (not below zero) by distributions, separately stated loss/deduction items, nondeductible noncapital expenses; the ordering and the stock-then-debt basis mechanics" },
  { cite: "IRC §1368", url: lii("1368"), type: "statute", taxYear: [2024, 2025, 2026], note: "distributions — for an S corp with NO accumulated earnings and profits, a distribution is tax-free to the extent of stock basis then capital gain; for an S corp WITH accumulated E&P, the accumulated adjustments account (AAA) ordering governs (AAA first as a return of basis, then E&P as a dividend, then remaining basis, then gain)" },
  { cite: "IRC §1374", url: lii("1374"), type: "statute", taxYear: [2024, 2025, 2026], note: "built-in gains tax — a former C corporation that elects S status owes a corporate-level tax (at the highest §11 rate) on net recognized built-in gain during the recognition period following conversion; capture the recognition-period rule and that the tax is at the corporate rate" },
  // ── ENTITY LAW — Subchapter K CORE (partnerships, the second-most-common entity; audit gap #1 continued).
  // Stable, non-OBBBA provisions. Capture the operative RULE (substantial economic effect, outside-basis
  // mechanics, the liability and §754 rules), not a worked example. ──
  { cite: "IRC §704", url: lii("704"), type: "statute", taxYear: [2024, 2025, 2026], note: "partner's distributive share — a partner's share of income, gain, loss, deduction, or credit is determined by the partnership agreement, but an allocation is respected only if it has SUBSTANTIAL ECONOMIC EFFECT (else it is reallocated by the partner's interest in the partnership). §704(c): built-in gain or loss on CONTRIBUTED property is allocated to the contributing partner. §704(d): a partner's distributive share of loss is allowed only to the extent of the partner's adjusted basis in the partnership interest, with the excess carried forward" },
  { cite: "IRC §705", url: lii("705"), type: "statute", taxYear: [2024, 2025, 2026], note: "adjusted basis of a partner's interest (OUTSIDE BASIS) — increased by the partner's distributive share of taxable income and tax-exempt income and by additional contributions, and decreased (not below zero) by distributions and by the partner's distributive share of losses and nondeductible noncapital expenses" },
  { cite: "IRC §722", url: lii("722"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis of a contributing partner's interest — a partner's basis in the partnership interest acquired by a contribution of property equals the money contributed plus the partner's adjusted basis in the contributed property at the time of contribution (carryover/substituted basis)" },
  { cite: "IRC §731", url: lii("731"), type: "statute", taxYear: [2024, 2025, 2026], note: "gain or loss on a distribution — a partner recognizes GAIN on a current distribution only to the extent money distributed EXCEEDS the partner's adjusted outside basis; a distribution of property is generally nontaxable; loss is recognized only on a liquidating distribution of money (and certain hot assets)" },
  { cite: "IRC §752", url: lii("752"), type: "statute", taxYear: [2024, 2025, 2026], note: "treatment of partnership LIABILITIES — an increase in a partner's share of partnership liabilities is treated as a contribution of money by that partner (raising outside basis); a decrease is treated as a distribution of money (lowering outside basis); recourse liabilities are allocated to the partner who bears the economic risk of loss, nonrecourse generally by profit share" },
  { cite: "IRC §754", url: lii("754"), type: "statute", taxYear: [2024, 2025, 2026], note: "election to adjust basis of partnership property — a partnership may elect to adjust the basis of its property on a transfer of an interest (§743(b)) and on a distribution (§734(b)); once made, the election applies to all such transfers and distributions until revoked with IRS consent" },
  // ── ENTITY LAW — Subchapter C CORE (C corporations; audit gap #1 continued). Distribution + incorporation
  // rules. (§312 E&P deferred: the substring section filter would collide with the existing §3121 chunk.) ──
  { cite: "IRC §301", url: lii("301"), type: "statute", taxYear: [2024, 2025, 2026], note: "distributions of property — under §301(c) a distribution to a shareholder is a DIVIDEND to the extent of the corporation's earnings and profits (§316); the part that is not a dividend is applied against and reduces the shareholder's stock basis (return of capital); any remaining excess is treated as gain from the sale of the stock" },
  { cite: "IRC §311", url: lii("311"), type: "statute", taxYear: [2024, 2025, 2026], note: "taxability of the corporation on a distribution — under §311(b) a corporation that distributes APPRECIATED property recognizes gain as if it had sold the property at fair market value; under §311(a) it does NOT recognize loss on a distribution of property" },
  { cite: "IRC §316", url: lii("316"), type: "statute", taxYear: [2024, 2025, 2026], note: "dividend defined — a dividend is any distribution of property a corporation makes to its shareholders out of earnings and profits, either accumulated after Feb 28 1913 or of the current taxable year; distributions are treated as made out of the most recently accumulated E&P" },
  { cite: "IRC §351", url: lii("351"), type: "statute", taxYear: [2024, 2025, 2026], note: "transfer to a controlled corporation — no gain or loss is recognized if property is transferred to a corporation by one or more persons SOLELY in exchange for its stock and, immediately after the exchange, those persons are in CONTROL (within the meaning of §368(c): at least 80% of total combined voting power and at least 80% of each other class) of the corporation" },
  { cite: "IRC §357", url: lii("357"), type: "statute", taxYear: [2024, 2025, 2026], note: "assumption of liability — in a §351 exchange the corporation's assumption of a transferor's liability is generally NOT treated as money or boot; but under §357(c) gain is recognized to the extent the liabilities assumed EXCEED the total adjusted basis of the property transferred, and under §357(b) the assumption is treated as boot if its principal purpose is tax avoidance or not a bona fide business purpose" },
  // ── CAPITAL GAINS / PROPERTY SPINE (the audit's biggest hole — foundational to almost every property
  // transaction). §1061 is the carried-interest rule a PE/hedge-fund question turns on. ──
  { cite: "IRC §1061", url: lii("1061"), type: "statute", taxYear: [2024, 2025, 2026], note: "carried interest / applicable partnership interest — to the extent a taxpayer holds an applicable partnership interest, the net long-term capital gain is RECHARACTERIZED as SHORT-TERM unless the relevant holding period is MORE THAN 3 YEARS (the rule substitutes a 3-year period for the normal 1-year period of §1222). So carried-interest gain on a position held 3 years or less is short-term; held MORE than 3 years it keeps long-term treatment. Capture the 3-year holding-period rule" },
  { cite: "IRC §1221", url: lii("1221"), type: "statute", taxYear: [2024, 2025, 2026], note: "capital asset DEFINED — property held by the taxpayer is a capital asset EXCEPT the enumerated exclusions: inventory / stock in trade / property held primarily for sale to customers; depreciable property and real property used in a trade or business (that is §1231 property, not a capital asset); accounts or notes receivable acquired in the ordinary course; certain self-created copyrights and similar property; and certain hedging transactions" },
  { cite: "IRC §1222", url: lii("1222"), type: "statute", taxYear: [2024, 2025, 2026], note: "long-term vs short-term DEFINED — a capital gain or loss is LONG-TERM if the asset was held for MORE THAN 1 YEAR, and SHORT-TERM if held for 1 year or less; defines net short-term and net long-term capital gain/loss and the netting terms" },
  { cite: "IRC §1231", url: lii("1231"), type: "statute", taxYear: [2024, 2025, 2026], note: "property used in a trade or business — the best-of-both rule: if §1231 gains EXCEED §1231 losses for the year, ALL are treated as LONG-TERM CAPITAL gains and losses; if losses equal or exceed gains, all are treated as ORDINARY. A non-recaptured net §1231 loss in the prior 5 years recharacterizes a later §1231 gain as ordinary to that extent (the §1231(c) lookback)" },
  { cite: "IRC §1245", url: lii("1245"), type: "statute", taxYear: [2024, 2025, 2026], note: "depreciation recapture on §1245 (personal / tangible business) property — on a disposition, gain is recaptured as ORDINARY income to the extent of prior depreciation or amortization taken (the lower of the depreciation taken or the gain realized); any remaining gain is §1231/capital" },
  { cite: "IRC §1250", url: lii("1250"), type: "statute", taxYear: [2024, 2025, 2026], note: "depreciation recapture on §1250 (depreciable REAL) property — ordinary-income recapture applies only to the EXCESS of accelerated depreciation over straight-line (generally zero for property placed in service after 1986 using straight-line); the previously deducted straight-line depreciation is 'unrecaptured §1250 gain' taxed as capital gain at a maximum 25% rate" },
  { cite: "IRC §1014", url: lii("1014"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis of property acquired from a DECEDENT — the basis is the property's FAIR MARKET VALUE at the date of the decedent's death (or the alternate valuation date if elected), i.e. a stepped-up (or stepped-down) basis; capture the FMV-at-death rule" },
  { cite: "IRC §1015", url: lii("1015"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis of property acquired by GIFT — the donee takes a CARRYOVER basis equal to the donor's adjusted basis (increased for gift tax paid on the appreciation); special dual-basis rule: if the donor's basis exceeds FMV at the gift date, the basis for determining a LOSS is that lower FMV" },
  // ── HIGH-FREQUENCY INDIVIDUAL / SMB PROVISIONS (next-ranked coverage after the capital-gains spine). ──
  { cite: "IRC §1041", url: lii("1041"), type: "statute", taxYear: [2024, 2025, 2026], note: "transfers between spouses or incident to divorce — NO gain or loss is recognized on a transfer of property to (or in trust for) a spouse, or a former spouse if incident to divorce; the transferee takes the transferor's adjusted basis (carryover/gift-like treatment), so the transfer is nonrecognition not a step-up" },
  { cite: "IRC §280A", url: lii("280A"), type: "statute", taxYear: [2024, 2025, 2026], note: "business use of a home (home-office) + dwelling rented — deductions for a dwelling unit the taxpayer uses as a residence are generally disallowed EXCEPT a portion used EXCLUSIVELY and on a REGULAR basis as the principal place of business, or to meet clients/customers, or a separate structure; the home-office deduction is limited to gross income from that use, with disallowed amounts carried forward. Also the rental rule: if a residence is rented fewer than 15 days, the rental income is excluded and no rental deductions are allowed" },
  { cite: "IRC §166", url: lii("166"), type: "statute", taxYear: [2024, 2025, 2026], note: "bad debt deduction — a business bad debt that becomes wholly or partially worthless is deductible as an ORDINARY deduction in the year of worthlessness; a NONBUSINESS bad debt is deductible only when TOTALLY worthless and is treated as a SHORT-TERM CAPITAL LOSS. Requires a bona fide debt (a debtor-creditor relationship), not a gift or contribution to capital" },
  { cite: "IRC §318", url: lii("318"), type: "statute", taxYear: [2024, 2025, 2026], note: "constructive ownership of stock (attribution) — for the provisions that apply it, a person is treated as owning stock owned by family members (spouse, children, grandchildren, and parents), and stock is attributed to and from partnerships, estates, trusts, and corporations (with a 50%-ownership threshold for corporate attribution); option holders are treated as owning the underlying stock" },
  { cite: "IRC §469", url: lii("469"), type: "statute", taxYear: [2024, 2025, 2026], note: "passive activity loss limitation — losses and credits from a PASSIVE activity (a trade or business in which the taxpayer does not MATERIALLY PARTICIPATE, and, generally, any rental activity) are deductible only to the extent of income from passive activities; disallowed passive losses are SUSPENDED and carried forward, and are allowed in full when the taxpayer disposes of the entire interest in the activity in a fully taxable transaction" },
  // ── CORE DEPRECIATION / DEDUCTION PROVISIONS (very high frequency in business + individual returns). ──
  { cite: "IRC §168", url: lii("168"), type: "statute", taxYear: [2024, 2025, 2026], note: "MACRS depreciation — tangible property is depreciated over its assigned recovery period using the applicable method (200% or 150% declining balance switching to straight-line for personal property; straight-line for real property) and convention (half-year, mid-quarter, or mid-month). §168(k) BONUS depreciation allows an additional first-year deduction equal to the applicable percentage of the adjusted basis of qualified property. Capture the MACRS framework + that §168(k) is the bonus/additional first-year allowance" },
  { cite: "IRC §179", url: lii("179"), type: "statute", taxYear: [2024, 2025, 2026], note: "election to expense — a taxpayer may ELECT to treat the cost of qualifying section 179 property (depreciable tangible personal property, and certain real property, acquired for use in the active conduct of a trade or business) as a current expense rather than capitalize and depreciate it, subject to an annual dollar limitation that is reduced (phased out) as the total cost of section 179 property placed in service exceeds a threshold, and limited to the taxable income from the active trade or business (excess carried forward)" },
  { cite: "IRC §453", url: lii("453"), type: "statute", taxYear: [2024, 2025, 2026], note: "installment method — for an installment sale (a disposition of property where at least one payment is received AFTER the close of the taxable year of the sale), gain is reported as payments are received: each payment includes income equal to the gross-profit ratio (gross profit divided by total contract price). Dealer dispositions, inventory, and publicly traded property do not qualify; depreciation recapture under §1245/§1250 is recognized in the year of sale regardless" },
  { cite: "IRC §165", url: lii("165"), type: "statute", taxYear: [2024, 2025, 2026], note: "losses — a deduction is allowed for any loss sustained during the taxable year and not compensated by insurance or otherwise. For an INDIVIDUAL, the deduction is limited to losses incurred in a trade or business, losses incurred in a transaction entered into for profit, and casualty or theft losses — and personal casualty losses are deductible only to the extent attributable to a federally declared disaster (post-TCJA). Capital losses are allowed only as provided in §§1211-1212; a worthless security is treated as a capital loss" },
  { cite: "IRC §170", url: lii("170"), type: "statute", taxYear: [2024, 2025, 2026], note: "charitable contribution deduction — a deduction is allowed for charitable contributions to qualified organizations, paid within the taxable year, subject to ADJUSTED-GROSS-INCOME percentage CEILINGS that depend on the donee and the property (cash to public charities up to 60% of AGI; capital-gain property generally limited to 30%, or 20% to certain organizations); contributions exceeding the ceiling carry forward up to 5 years, and contributions of $250 or more require contemporaneous written acknowledgment" },
  // ── EQUITY COMPENSATION (the §409A gap surfaced live: discounted options / ISOs / restricted stock). ──
  { cite: "IRC §83", url: lii("83"), type: "statute", taxYear: [2024, 2025, 2026], note: "property transferred for services — the excess of the property's FAIR MARKET VALUE over the amount paid is included in the service provider's gross income in the first year the property is either TRANSFERABLE or NO LONGER SUBJECT TO A SUBSTANTIAL RISK OF FORFEITURE (i.e. when it vests). Under the §83(b) election the service provider may instead elect to include the spread at the time of transfer (grant); the election must be made within 30 DAYS of the transfer" },
  { cite: "IRC §409A", url: lii("409A"), type: "statute", taxYear: [2024, 2025, 2026], note: "nonqualified deferred compensation — if an NQDC plan fails to meet the §409A distribution, acceleration, and election requirements, all compensation deferred under the plan (to the extent not subject to a substantial risk of forfeiture and not previously included) is INCLUDED IN GROSS INCOME, and the tax for that year is INCREASED by an ADDITIONAL 20% of the amount included PLUS a premium-interest charge. A stock option with an exercise price below FMV at grant is generally nonqualified deferred compensation subject to §409A. Capture the income-inclusion-when-vested rule + the additional 20% tax" },
  { cite: "IRC §421", url: lii("421"), type: "statute", taxYear: [2024, 2025, 2026], note: "general rules for STATUTORY stock options — when a share is transferred to an individual on exercise of a statutory option (an incentive stock option under §422 or an employee stock purchase plan option under §423) and the holding-period requirements are met, NO income is recognized at exercise for regular tax and the employer gets no deduction; gain is generally capital on a later sale" },
  { cite: "IRC §422", url: lii("422"), type: "statute", taxYear: [2024, 2025, 2026], note: "INCENTIVE STOCK OPTIONS (ISOs) — to qualify: granted under a shareholder-approved plan to an employee; the option PRICE must be at least the FAIR MARKET VALUE of the stock at grant; the option must be exercisable within 10 years; and the aggregate FMV (determined at grant) of stock for which ISOs are first exercisable in any calendar year may not exceed $100,000 (the excess is treated as a nonstatutory option). For a more-than-10% shareholder, the price must be at least 110% of FMV and the term no more than 5 years. A below-FMV strike disqualifies ISO treatment" },
  { cite: "IRC §423", url: lii("423"), type: "statute", taxYear: [2024, 2025, 2026], note: "EMPLOYEE STOCK PURCHASE PLANS (ESPPs) — a qualified §423 plan must be available to employees on equal terms; the option PRICE may not be less than the LESSER of 85% of the FMV at grant or 85% of the FMV at exercise; and no employee may accrue the right to purchase more than $25,000 of stock (FMV at grant) per calendar year" },
  { cite: "IRC §424", url: lii("424"), type: "statute", taxYear: [2024, 2025, 2026], note: "definitions and special rules for statutory stock options — defines a permitted modification/extension/renewal (a modification is treated as the grant of a NEW option), substitutions and assumptions in corporate transactions, the meaning of disposition, and the stock-attribution rules used for the §422 more-than-10%-shareholder test" },
  // ── WAVE 1 (bulk tier-1 statute breadth — the coverage-map's first pass). High-frequency gaps. ──
  { cite: "IRC §162", url: lii("162"), type: "statute", taxYear: [2024, 2025, 2026], note: "trade or business expenses — a deduction is allowed for all the ORDINARY AND NECESSARY expenses paid or incurred during the year in carrying on a trade or business, including a reasonable allowance for salaries, traveling expenses while away from home, and rentals; disallowed items include illegal bribes/kickbacks, fines and penalties paid to a government, lobbying, and (per §162(m)) compensation over $1,000,000 for certain public-company executives" },
  { cite: "IRC §195", url: lii("195"), type: "statute", taxYear: [2024, 2025, 2026], note: "start-up expenditures — must generally be capitalized, but a taxpayer may ELECT to deduct up to $5,000 of start-up costs in the year the active trade or business begins (reduced dollar-for-dollar as total start-up costs exceed $50,000), and amortize the remainder ratably over 180 months" },
  { cite: "IRC §212", url: lii("212"), type: "statute", taxYear: [2024, 2025, 2026], note: "expenses for the production of income — a deduction is allowed for ordinary and necessary expenses paid for the production or collection of income, for the management/conservation of income-producing property, or in connection with the determination/collection/refund of any tax (note many §212 miscellaneous itemized deductions are suspended for individuals 2018-2025 under §67(g))" },
  { cite: "IRC §132", url: lii("132"), type: "statute", taxYear: [2024, 2025, 2026], note: "certain fringe benefits excluded from gross income — no-additional-cost services, qualified employee discounts, working-condition fringes, de minimis fringes, qualified transportation fringes, on-premises athletic facilities, and (suspended 2018-2025) qualified moving-expense reimbursements; nondiscrimination rules apply to several categories" },
  { cite: "IRC §274", url: lii("274"), type: "statute", taxYear: [2024, 2025, 2026], note: "disallowance of certain entertainment / meal expenses — NO deduction for ENTERTAINMENT, amusement, or recreation; business MEALS are generally limited to 50% (subject to substantiation); reimbursed expenses, recreational employee events, and de minimis items have exceptions; strict substantiation is required for travel, meals, and listed property" },
  { cite: "IRC §267", url: lii("267"), type: "statute", taxYear: [2024, 2025, 2026], note: "losses and expenses between RELATED parties — no deduction is allowed for a loss on a sale or exchange between related persons (family members, an individual and a controlled corporation, etc.); the disallowed loss may offset gain when the transferee later disposes of the property; and an accrual-method payor may not deduct an expense owed to a related cash-method payee until it is includible in the payee's income" },
  { cite: "IRC §312", url: lii("312"), type: "statute", taxYear: [2024, 2025, 2026], note: "EARNINGS AND PROFITS (E&P) — the account that measures a corporation's capacity to pay a dividend under §316. E&P is increased by income and decreased by distributions; this section prescribes the adjustments (e.g. E&P generally uses straight-line depreciation, and is reduced by the money plus the adjusted basis (or, if greater for appreciated property, FMV) of property distributed)" },
  { cite: "IRC §721", url: lii("721"), type: "statute", taxYear: [2024, 2025, 2026], note: "contribution to a partnership — NO gain or loss is recognized to a partnership or to any of its partners on a contribution of property to the partnership in exchange for an interest in the partnership (nonrecognition; the partner's basis carries over under §722 and the partnership's basis under §723); does not apply to a transfer to an investment-company partnership" },
  { cite: "IRC §751", url: lii("751"), type: "statute", taxYear: [2024, 2025, 2026], note: "unrealized receivables and inventory items (HOT ASSETS) — on a sale of a partnership interest or certain distributions, the amount attributable to the partnership's unrealized receivables and inventory items is treated as ORDINARY income, not capital gain, overriding the general capital-gain character of a partnership-interest sale" },
  { cite: "IRC §358", url: lii("358"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis to the transferor/distributee in a nonrecognition exchange — in a §351 incorporation or a reorganization, the transferor's basis in the stock received equals the adjusted basis of the property transferred, decreased by money received and the FMV of other property (boot) received, and increased by any gain recognized (a substituted basis)" },
  // ── WAVE 1 batch 2 (high-frequency individual + SMB statute gaps). ──
  { cite: "IRC §152", url: lii("152"), type: "statute", taxYear: [2024, 2025, 2026], note: "dependent defined — a dependent is a QUALIFYING CHILD or a QUALIFYING RELATIVE. A qualifying child must meet the relationship, age (generally under 19, or under 24 if a full-time student, or any age if permanently and totally disabled), residency (same principal place of abode more than half the year), and support tests, and not file a joint return. A qualifying relative must meet a relationship-or-member-of-household test, a gross-income test (income below the exemption amount), and a support test (the taxpayer provides more than half the support)" },
  { cite: "IRC §172", url: lii("172"), type: "statute", taxYear: [2024, 2025, 2026], note: "net operating loss deduction — a net operating loss (the excess of allowable deductions over gross income) may be carried forward to offset income in later years. Post-TCJA, NOLs arising in years after 2017 generally have NO carryback (limited exceptions) and an UNLIMITED carryforward, but an NOL deduction from those years is limited to 80% of taxable income (computed without the NOL deduction)" },
  { cite: "IRC §1211", url: lii("1211"), type: "statute", taxYear: [2024, 2025, 2026], note: "limitation on capital losses — a CORPORATION may deduct capital losses only to the extent of capital gains. An INDIVIDUAL (other taxpayer) may deduct capital losses to the extent of capital gains PLUS up to $3,000 ($1,500 for married filing separately) of ordinary income" },
  { cite: "IRC §1212", url: lii("1212"), type: "statute", taxYear: [2024, 2025, 2026], note: "capital loss carryovers — an individual's net capital loss disallowed by the §1211 $3,000 limit is CARRIED FORWARD indefinitely, retaining its short-term or long-term character. A corporation's net capital loss is generally carried BACK 3 years and FORWARD 5 years, treated as a short-term capital loss" },
  { cite: "IRC §72", url: lii("72"), type: "statute", taxYear: [2024, 2025, 2026], note: "annuities and distributions from retirement plans — distributions are taxed under an exclusion-ratio/basis-recovery rule; amounts attributable to nondeductible contributions (investment in the contract) are recovered tax-free. §72(t) imposes an ADDITIONAL 10% tax on early distributions from a qualified plan or IRA made before age 59½, subject to enumerated exceptions (death, disability, substantially equal periodic payments, certain medical, first-home/education for IRAs, etc.)" },
  { cite: "IRC §408", url: lii("408"), type: "statute", taxYear: [2024, 2025, 2026], note: "individual retirement accounts (IRAs) — a traditional IRA is a tax-exempt trust for an individual's retirement; contributions may be deductible under §219 and distributions are generally taxable; rules cover rollovers (generally one 60-day rollover per 12 months), required minimum distributions, and prohibited transactions; a SIMPLE IRA and SEP have separate contribution rules" },
  { cite: "IRC §6695", url: lii("6695"), type: "statute", taxYear: [2024, 2025, 2026], note: "other assessable penalties on tax-return PREPARERS — separate penalties for failure to furnish a copy to the taxpayer, failure to sign the return, failure to furnish the preparer's identifying number, failure to retain a copy/list, and (§6695(g)) failure to comply with the DUE-DILIGENCE requirements for the EITC, child tax credit, American Opportunity credit, and head-of-household status" },
  { cite: "IRC §7701", url: lii("7701"), type: "statute", taxYear: [2024, 2025, 2026], note: "definitions — provides the Code's general definitions (person, partnership, corporation, trade or business, fiduciary, United States person, etc.). §7701(o) codifies the ECONOMIC SUBSTANCE doctrine (a transaction has economic substance only if it changes the taxpayer's economic position in a meaningful way apart from tax effects and the taxpayer had a substantial non-tax purpose). The entity-classification ('check-the-box') rules are in the regulations under this section" },
  { cite: "IRC §243", url: lii("243"), type: "statute", taxYear: [2024, 2025, 2026], note: "dividends-received deduction (DRD) — a C corporation that receives dividends from another taxable domestic corporation may deduct a percentage of the dividends: 50% generally, 65% if it owns at least 20% of the payer, and 100% for dividends from a member of the same affiliated group; the DRD is subject to a taxable-income limitation and a holding-period requirement" },
  { cite: "IRC §305", url: lii("305"), type: "statute", taxYear: [2024, 2025, 2026], note: "distributions of stock and stock rights — a stock dividend (a corporation's distribution of its own stock to shareholders) is generally NOT included in gross income, EXCEPT where the distribution is in lieu of money (elective), is disproportionate (some shareholders receive stock while others receive cash/property), is on preferred stock, or otherwise increases some shareholders' proportionate interests" },
  // ── WAVE 1 batch 3 (basis fundamentals, retirement, health benefits, entity-basis gaps). ──
  { cite: "IRC §1001", url: lii("1001"), type: "statute", taxYear: [2024, 2025, 2026], note: "determination of gain or loss — gain is the excess of the AMOUNT REALIZED over the adjusted basis; loss is the excess of adjusted basis over amount realized. Amount realized is the money plus the fair market value of other property received. Except as otherwise provided, the ENTIRE amount of gain or loss on a sale or exchange of property is RECOGNIZED" },
  { cite: "IRC §1012", url: lii("1012"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis of property — COST basis: the basis of property is its cost, except as otherwise provided. For stock, basis may be determined by specific identification or, by default for certain shares, an average-basis or first-in-first-out convention" },
  { cite: "IRC §1016", url: lii("1016"), type: "statute", taxYear: [2024, 2025, 2026], note: "adjustments to basis — basis is properly ADJUSTED for items such as capital expenditures and improvements (increase) and for depreciation, amortization, depletion, and returns of capital allowed or allowable (decrease, but not below zero), among other enumerated adjustments" },
  { cite: "IRC §401", url: lii("401"), type: "statute", taxYear: [2024, 2025, 2026], note: "qualified pension, profit-sharing, and stock-bonus plans — to be QUALIFIED (and thus tax-favored), a plan must be for the exclusive benefit of employees, meet minimum participation, coverage, vesting, and nondiscrimination requirements, and satisfy contribution/benefit limits; §401(k) permits a cash-or-deferred arrangement under which employees may elect to defer compensation into the plan" },
  { cite: "IRC §125", url: lii("125"), type: "statute", taxYear: [2024, 2025, 2026], note: "cafeteria plans — a written plan under which employees may CHOOSE between cash and qualified nontaxable benefits (e.g. health coverage, a health flexible spending arrangement, dependent-care assistance); a participant's election of a qualified benefit is not included in gross income merely because cash was available, provided the plan meets eligibility and nondiscrimination rules" },
  { cite: "IRC §105", url: lii("105"), type: "statute", taxYear: [2024, 2025, 2026], note: "amounts received under accident and health plans — amounts received by an employee through EMPLOYER-FUNDED accident or health insurance are generally included in income, EXCEPT amounts that reimburse the employee for medical care (§213(d)) of the employee, spouse, or dependents, or that are payments for permanent loss/disfigurement computed without regard to time absent from work" },
  { cite: "IRC §106", url: lii("106"), type: "statute", taxYear: [2024, 2025, 2026], note: "contributions by employer to accident and health plans — the EXCLUSION from an employee's gross income of employer-provided coverage under an accident or health plan; employer-paid health insurance premiums are not income to the employee" },
  { cite: "IRC §332", url: lii("332"), type: "statute", taxYear: [2024, 2025, 2026], note: "complete liquidation of a SUBSIDIARY — no gain or loss is recognized to a PARENT corporation on the receipt of property in a complete liquidation of a subsidiary in which the parent owns at least 80% (vote and value), provided the distribution is in cancellation of stock; the subsidiary also generally recognizes no gain or loss under §337, and the parent takes a carryover basis under §334(b)" },
  { cite: "IRC §362", url: lii("362"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis to a CORPORATION of property received — on a §351 transfer or as a contribution to capital, the corporation's basis in the property equals the transferor's adjusted basis increased by any gain the transferor recognized; an anti-loss-importation/built-in-loss rule limits an aggregate basis in excess of the property's FMV" },
  { cite: "IRC §723", url: lii("723"), type: "statute", taxYear: [2024, 2025, 2026], note: "basis of property contributed to a PARTNERSHIP — the partnership's basis in property contributed by a partner is the contributing partner's adjusted basis at the time of contribution (a carryover/transferred basis), increased by any gain the contributing partner recognized under §721(b)" },
  // ── WAVE 2 (TREASURY REGULATIONS — the §6662 authority-weighting fuel). delegationBasis tags the
  // post-Loper-Bright strength: express (specific statutory grant) keeps full weight; general_7805
  // (interpretive) is contestable. These wake the dormant DELEGATION_FACTOR in lib/tax/authority/weighting.ts. ──
  { cite: "Treas. Reg. §1.6662-4", url: cfr("1.6662-4"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "general_7805", note: "the SUBSTANTIAL-AUTHORITY standard for the §6662 accuracy penalty — substantial authority exists only if the WEIGHT of authorities supporting the treatment is substantial in relation to the weight of contrary authorities; an OBJECTIVE standard more stringent than reasonable basis but less stringent than more-likely-than-not; lists the types that count as authority (the Code, regulations, court cases, revenue rulings/procedures, etc.) and that a conclusion in a treatise or a tax professional's opinion is NOT authority" },
  { cite: "Treas. Reg. §1.6664-4", url: cfr("1.6664-4"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "general_7805", note: "the REASONABLE-CAUSE and good-faith exception to the §6662 penalty — no penalty applies to a portion of an underpayment for which the taxpayer shows reasonable cause and acted in good faith; the determination is made case by case, the most important factor being the extent of the taxpayer's effort to assess the proper tax liability; reasonable reliance on professional advice can qualify if based on all pertinent facts" },
  { cite: "Treas. Reg. §1.199A-1", url: cfr("1.199A-1"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "express", note: "operational rules for the §199A qualified business income deduction — defines qualified business income (QBI), the combined QBI amount, and the deduction equal to the lesser of 20% of QBI plus 20% of qualified REIT dividends/PTP income, or 20% of taxable income over net capital gain; coordinates the W-2-wage and UBIA limits and the SSTB rules for taxpayers above the threshold" },
  { cite: "Treas. Reg. §1.469-5T", url: cfr("1.469-5T"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "express", note: "the seven tests for MATERIAL PARTICIPATION in a §469 activity — an individual materially participates if they participate more than 500 hours in the year; OR their participation is substantially all the participation; OR more than 100 hours and not less than any other individual; OR it is a significant-participation activity aggregating over 500 hours; OR material participation in any 5 of the prior 10 years; OR (personal service activity) any 3 prior years; OR a facts-and-circumstances regular/continuous/substantial test" },
  { cite: "Treas. Reg. §1.704-1", url: cfr("1.704-1"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "express", note: "the SUBSTANTIAL-ECONOMIC-EFFECT safe harbor for partnership allocations under §704(b) — an allocation has economic effect only if the partnership maintains capital accounts under the regulatory rules, liquidates according to positive capital-account balances, and requires a partner with a deficit to restore it (or the allocation meets a qualified income offset); 'substantiality' requires a reasonable possibility the allocation substantially affects the dollars the partners receive independent of tax consequences" },
  { cite: "Treas. Reg. §301.7701-3", url: cfr("301.7701-3"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "general_7805", note: "entity classification ('CHECK-THE-BOX') — an eligible entity with two or more members defaults to a PARTNERSHIP or may elect to be an association taxable as a corporation; a single-member eligible entity defaults to DISREGARDED as separate from its owner or may elect corporate treatment; the election is filed on Form 8832 and an entity generally may not change its election again during the 60 months after a prior election" },
  { cite: "Treas. Reg. §1.83-7", url: cfr("1.83-7"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "general_7805", note: "taxation of NONQUALIFIED (nonstatutory) stock options under §83 — if the option has a readily ascertainable fair market value at grant, §83(a) applies at grant; if it does NOT (the usual case, e.g. private-company options), there is no tax at grant and §83 applies at EXERCISE, taxing the spread between the stock's fair market value and the amount paid" },
  { cite: "Treas. Reg. §1.409A-1", url: cfr("1.409A-1"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "express", anchor: "may never be less than the fair market value", note: "definitions for §409A nonqualified deferred compensation, including the STOCK-RIGHTS rule — a stock option or stock appreciation right is NOT deferred compensation subject to §409A only if the exercise price may never be less than the fair market value of the underlying stock on the date the right is granted (and the number of shares is fixed); a DISCOUNTED option (an exercise price below grant-date fair market value) therefore IS nonqualified deferred compensation subject to §409A" },
  { cite: "Treas. Reg. §1.162-1", url: cfr("1.162-1"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "general_7805", note: "business expenses under §162 — ordinary and necessary expenses of carrying on a trade or business are deductible, including a reasonable allowance for salaries, repairs that do not add value or prolong useful life, rent, and other operating costs; capital expenditures, personal expenses, and amounts otherwise disallowed are not deductible" },
  { cite: "Treas. Reg. §1.61-1", url: cfr("1.61-1"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "general_7805", note: "gross income under §61 — gross income means all income from whatever source derived, realized in any form, whether in money, property, or services; it includes income realized in any form unless a specific statutory exclusion applies" },
  { cite: "Treas. Reg. §1.752-2", url: cfr("1.752-2"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "express", note: "ALLOCATION OF RECOURSE PARTNERSHIP LIABILITIES — a partner's share of a recourse liability equals the portion for which that partner (or a related person) bears the ECONOMIC RISK OF LOSS, determined by a constructive-liquidation analysis (all assets worthless, all liabilities due, the partnership liquidates): a partner bears the risk to the extent of any net payment obligation (e.g., a deficit-restoration obligation or a guarantee) that would not be reimbursed" },
  { cite: "Treas. Reg. §1.707-3", url: cfr("1.707-3"), type: "regulation", taxYear: [2024, 2025, 2026], delegationBasis: "express", note: "DISGUISED SALES of property to a partnership — a partner's transfer of property to a partnership and a related transfer of money or other consideration to the partner are recharacterized as a SALE (in whole or part) if, based on all the facts, the two transfers together are properly characterized as a sale; transfers within TWO YEARS of each other are PRESUMED to be a sale (rebuttable), and transfers more than two years apart are presumed not to be" },
  // ── EMPTY-AREA DISTILL (international / estate / accounting) — the PROVEN answerable path: distilled operative
  // rules ANSWER where raw full-text only retrieves. Fills the benchmark's empty shelves through the figure gate. ──
  { cite: "IRC §901", url: lii("901"), type: "statute", taxYear: [2024, 2025, 2026], note: "FOREIGN TAX CREDIT — a US taxpayer may ELECT to credit (in lieu of deducting) income, war-profits, and excess-profits taxes paid or accrued to any foreign country or US possession against US tax; the credit is subject to the §904 limitation and the choice between credit and deduction applies to ALL such foreign taxes for the year" },
  { cite: "IRC §904", url: lii("904"), type: "statute", taxYear: [2024, 2025, 2026], note: "FTC LIMITATION — the foreign tax credit may not exceed US tax multiplied by the ratio of foreign-source taxable income to total taxable income, computed SEPARATELY for each statutory category (basket): passive category income and general category income (plus the GILTI and foreign-branch baskets); excess credits carry BACK 1 year and FORWARD 10 years" },
  { cite: "IRC §951A", url: lii("951A"), type: "statute", taxYear: [2024, 2025, 2026], note: "GILTI — a US shareholder of a controlled foreign corporation must include in gross income its global intangible low-taxed income for the year; GILTI equals the shareholder's net CFC tested income OVER its net deemed tangible income return (10% of qualified business asset investment (QBAI) reduced by certain interest expense)" },
  { cite: "IRC §250", url: lii("250"), type: "statute", taxYear: [2024, 2025, 2026], note: "FDII + GILTI DEDUCTION — a domestic C corporation may deduct a percentage of its foreign-derived intangible income (FDII) plus a percentage of its GILTI inclusion (37.5% FDII / 50% GILTI for years before 2026; reduced thereafter); the deduction is limited to taxable income" },
  { cite: "IRC §2001", url: lii("2001"), type: "statute", taxYear: [2024, 2025, 2026], note: "ESTATE TAX IMPOSED — a tax is imposed on the transfer of the taxable estate of every decedent who is a citizen or resident; computed as a tentative tax on the sum of the taxable estate plus adjusted taxable gifts at the rate schedule (top rate 40%), reduced by gift taxes payable and the unified credit" },
  { cite: "IRC §2010", url: lii("2010"), type: "statute", taxYear: [2024, 2025, 2026], note: "UNIFIED CREDIT against estate tax — the applicable credit amount equals the tentative tax on the applicable exclusion amount (the basic exclusion amount, inflation-indexed, plus any deceased spousal unused exclusion (DSUE) elected via portability)" },
  { cite: "IRC §2503", url: lii("2503"), type: "statute", taxYear: [2024, 2025, 2026], note: "TAXABLE GIFTS — taxable gifts are the total gifts made during the calendar year less the ANNUAL EXCLUSION (an inflation-indexed amount per donee, available only for gifts of a PRESENT interest); also covers the §2503(c) minor's trust and that qualified tuition/medical transfers paid directly are not gifts" },
  { cite: "IRC §2056", url: lii("2056"), type: "statute", taxYear: [2024, 2025, 2026], note: "MARITAL DEDUCTION — an UNLIMITED deduction from the gross estate for the value of property passing to the surviving spouse, provided the interest is not a nondeductible terminable interest (a QTIP election under §2056(b)(7) qualifies a life estate); for a non-citizen spouse a qualified domestic trust (QDOT) is required" },
  { cite: "IRC §446", url: lii("446"), type: "statute", taxYear: [2024, 2025, 2026], note: "METHODS OF ACCOUNTING — taxable income is computed under the method of accounting the taxpayer regularly uses to keep its books, IF that method clearly reflects income; permissible methods include cash receipts and disbursements, accrual, or a permitted combination; a change in method requires the consent of the Secretary" },
  { cite: "IRC §451", url: lii("451"), type: "statute", taxYear: [2024, 2025, 2026], note: "TIMING OF INCOME — an accrual-method taxpayer includes an item in income when ALL EVENTS have occurred that fix the right to receive it and the amount can be determined with reasonable accuracy (the all-events test), no later than when taken into account on its financial statement; advance payments may be deferred one year under §451(c)" },
  { cite: "IRC §461", url: lii("461"), type: "statute", taxYear: [2024, 2025, 2026], note: "TIMING OF DEDUCTIONS — an accrual-method taxpayer may deduct a liability when the all-events test is met (the liability is fixed and the amount determinable) AND ECONOMIC PERFORMANCE has occurred (§461(h)); the §461(l) excess-business-loss limitation defers losses of noncorporate taxpayers above a threshold" },
  { cite: "IRC §263A", url: lii("263A"), type: "statute", taxYear: [2024, 2025, 2026], note: "UNIFORM CAPITALIZATION (UNICAP) — direct costs and a proper share of indirect costs allocable to real or tangible personal property PRODUCED by the taxpayer, or property ACQUIRED FOR RESALE, must be CAPITALIZED into the cost of the property (inventory), not currently deducted; a small-business exception applies to taxpayers under the §448(c) gross-receipts threshold" },
  // ── EMPTY-AREA DISTILL batch 2 (Subpart F / PFIC, estate valuation+deductions+GST, accounting, exempt/UBIT) ──
  { cite: "IRC §954", url: lii("954"), type: "statute", taxYear: [2024, 2025, 2026], note: "SUBPART F INCOME — foreign base company income of a CFC, which a US shareholder includes currently: foreign personal holding company income (FPHCI: dividends, interest, rents, royalties, annuities, net gains), foreign base company sales income, and foreign base company services income; subject to a de minimis and full-inclusion test and the high-tax exception" },
  { cite: "IRC §956", url: lii("956"), type: "statute", taxYear: [2024, 2025, 2026], note: "INVESTMENT OF EARNINGS IN US PROPERTY — a US shareholder of a CFC includes in income its pro-rata share of the CFC's average investment in US property (e.g., a loan to or stock/obligation of a US affiliate, tangible US property) to the extent of the CFC's applicable earnings, treated like a deemed dividend" },
  { cite: "IRC §965", url: lii("965"), type: "statute", taxYear: [2024, 2025, 2026], note: "TRANSITION TAX — the one-time deemed repatriation requiring a US shareholder to include accumulated post-1986 deferred foreign income of specified foreign corporations, taxed at reduced effective rates (15.5% on cash/cash-equivalents, 8% on the remainder) via a participation deduction, with an election to pay in installments" },
  { cite: "IRC §1291", url: lii("1291"), type: "statute", taxYear: [2024, 2025, 2026], note: "PFIC EXCESS-DISTRIBUTION REGIME — absent a QEF (§1295) or mark-to-market (§1296) election, a US person's excess distributions from, and gain on disposition of, a passive foreign investment company are allocated ratably over the holding period, taxed at the highest ordinary rate for prior years, plus an interest charge on the deferred tax" },
  { cite: "IRC §2031", url: lii("2031"), type: "statute", taxYear: [2024, 2025, 2026], note: "GROSS ESTATE VALUATION — the value of the gross estate is the fair market value of all the decedent's property (real, tangible personal, and intangible) at the date of death (or the §2032 alternate valuation date if elected); special rules apply to certain stock and life-insurance/annuity interests" },
  { cite: "IRC §2053", url: lii("2053"), type: "statute", taxYear: [2024, 2025, 2026], note: "ESTATE DEDUCTIONS — the taxable estate is determined by deducting from the gross estate funeral expenses, administration expenses, claims against the estate, and unpaid mortgages or indebtedness on property whose full value is in the gross estate, to the extent allowable under local law" },
  { cite: "IRC §2055", url: lii("2055"), type: "statute", taxYear: [2024, 2025, 2026], note: "ESTATE CHARITABLE DEDUCTION — an UNLIMITED deduction from the gross estate for the value of property transferred to or for the use of qualified charitable, religious, scientific, educational, or governmental organizations; split-interest transfers must meet the charitable-remainder/lead-trust requirements" },
  { cite: "IRC §2601", url: lii("2601"), type: "statute", taxYear: [2024, 2025, 2026], note: "GENERATION-SKIPPING TRANSFER TAX — a GST tax is imposed on every generation-skipping transfer (a direct skip, a taxable distribution, or a taxable termination) to a skip person (a beneficiary two or more generations below the transferor), at the maximum estate-tax rate, against which a GST exemption may be allocated" },
  { cite: "IRC §481", url: lii("481"), type: "statute", taxYear: [2024, 2025, 2026], note: "ADJUSTMENTS ON A CHANGE OF ACCOUNTING METHOD — when a taxpayer changes its method of accounting, a §481(a) adjustment is required to prevent amounts from being duplicated or omitted; a net positive adjustment is generally taken into income ratably over four years (a net negative adjustment in the year of change)" },
  { cite: "IRC §471", url: lii("471"), type: "statute", taxYear: [2024, 2025, 2026], note: "INVENTORIES — whenever the production, purchase, or sale of merchandise is an income-producing factor, inventories must be used and taken on a basis that conforms as nearly as may be to the best accounting practice in the trade and most clearly reflects income; a small-business exception applies under §471(c)" },
  { cite: "IRC §501", url: lii("501"), type: "statute", taxYear: [2024, 2025, 2026], note: "EXEMPT ORGANIZATIONS — §501(a) exempts from federal income tax the organizations described in §501(c), including §501(c)(3) corporations organized and operated EXCLUSIVELY for charitable, religious, educational, or scientific purposes, no part of whose net earnings inures to a private shareholder and which do not substantially lobby or intervene in political campaigns" },
  { cite: "IRC §512", url: lii("512"), type: "statute", taxYear: [2024, 2025, 2026], note: "UNRELATED BUSINESS TAXABLE INCOME (UBTI) — the gross income an exempt organization derives from an unrelated trade or business regularly carried on, less the deductions directly connected with it; modifications EXCLUDE most passive investment income (dividends, interest, royalties, and certain rents) unless debt-financed under §514" },
  { cite: "IRC §514", url: lii("514"), type: "statute", taxYear: [2024, 2025, 2026], note: "DEBT-FINANCED PROPERTY — income from debt-financed property held by an exempt organization is included in UBTI in the proportion that the average acquisition indebtedness bears to the average adjusted basis of the property (the debt/basis fraction), pulling otherwise-excluded passive income back into UBTI" },
  // ── EMPTY-AREA DISTILL batch 3 (international sourcing/DRD, estate valuation/inclusion/disclaimer, property nonrecognition, procedure) ──
  { cite: "IRC §861", url: lii("861"), type: "statute", taxYear: [2024, 2025, 2026], note: "SOURCE — income FROM SOURCES WITHIN the US: interest from the US or a US resident/domestic corp; dividends from a domestic corporation; compensation for services PERFORMED in the US; rents/royalties for property used in the US; gains on US real property; plus the allocation/apportionment of deductions against US-source income" },
  { cite: "IRC §863", url: lii("863"), type: "statute", taxYear: [2024, 2025, 2026], note: "SOURCE — special rules: items not specified in §§861-862 are sourced under regulations; income partly from US and partly foreign sources is allocated/apportioned; rules for transportation, space/ocean, and international communications income" },
  { cite: "IRC §865", url: lii("865"), type: "statute", taxYear: [2024, 2025, 2026], note: "SOURCE OF PERSONAL-PROPERTY SALES — gain from the sale of personal property is generally sourced by the RESIDENCE of the seller (US resident → US source); exceptions for inventory (title-passage/where produced), depreciable property (recapture US-sourced), intangibles, and goodwill" },
  { cite: "IRC §245A", url: lii("245A"), type: "statute", taxYear: [2024, 2025, 2026], note: "FOREIGN-SOURCE DIVIDEND DEDUCTION (participation exemption) — a domestic C corporation may deduct 100% of the foreign-source portion of dividends received from a specified 10%-owned foreign corporation, subject to a one-year holding-period requirement; effectively exempts qualifying foreign earnings from US tax" },
  { cite: "IRC §2032", url: lii("2032"), type: "statute", taxYear: [2024, 2025, 2026], note: "ALTERNATE VALUATION — the executor may ELECT to value the gross estate as of 6 months after death (property disposed of earlier is valued at disposition); the election is allowed only if it DECREASES both the value of the gross estate and the combined estate + GST tax" },
  { cite: "IRC §2036", url: lii("2036"), type: "statute", taxYear: [2024, 2025, 2026], note: "TRANSFERS WITH A RETAINED LIFE ESTATE — the gross estate includes the value of property the decedent transferred (other than for full consideration) but RETAINED for life the possession/enjoyment or the income, or the right to designate who enjoys it; pulls back lifetime transfers with strings attached" },
  { cite: "IRC §2518", url: lii("2518"), type: "statute", taxYear: [2024, 2025, 2026], note: "QUALIFIED DISCLAIMERS — an irrevocable and unqualified WRITTEN refusal to accept an interest, made within 9 MONTHS of the transfer (or the beneficiary turning 21), before accepting any benefits, passing without the disclaimant's direction — is treated as if the interest had never passed to the disclaimant" },
  { cite: "IRC §1033", url: lii("1033"), type: "statute", taxYear: [2024, 2025, 2026], note: "INVOLUNTARY CONVERSIONS — gain on property compulsorily/involuntarily converted (destruction, theft, condemnation) into money is NOT recognized to the extent the taxpayer reinvests the proceeds in property similar or related in service or use within the replacement period (generally 2 years, 3 for condemned real property)" },
  { cite: "IRC §1060", url: lii("1060"), type: "statute", taxYear: [2024, 2025, 2026], note: "APPLICABLE ASSET ACQUISITIONS — in a sale of a trade or business, both buyer and seller must allocate the consideration among the acquired assets under the RESIDUAL METHOD (by asset class, goodwill/going-concern last), and must use a CONSISTENT allocation; reported on Form 8594" },
  { cite: "IRC §1091", url: lii("1091"), type: "statute", taxYear: [2024, 2025, 2026], note: "WASH SALES — a loss on the sale of stock or securities is DISALLOWED if, within 30 days before or after, the taxpayer acquires substantially identical stock or securities (a 61-day window); the disallowed loss is ADDED to the basis of the replacement stock" },
  { cite: "IRC §1235", url: lii("1235"), type: "statute", taxYear: [2024, 2025, 2026], note: "SALE OF PATENTS — a holder's transfer of ALL SUBSTANTIAL RIGHTS to a patent (or an undivided interest therein) is treated as the sale of a LONG-TERM capital asset, regardless of the holding period or whether payments are contingent on use; the holder must be the creator or certain backers" },
  { cite: "IRC §6511", url: lii("6511"), type: "statute", taxYear: [2024, 2025, 2026], note: "LIMITATIONS ON REFUND CLAIMS — a claim for credit or refund must be filed within 3 YEARS from the time the return was filed or 2 YEARS from the time the tax was paid, whichever is later; the refund amount is capped by a lookback period tied to which limit applies" },
  { cite: "IRC §6321", url: lii("6321"), type: "statute", taxYear: [2024, 2025, 2026], note: "FEDERAL TAX LIEN — if any person liable to pay a tax neglects or refuses to pay after demand, the amount (including interest and penalties) is a LIEN in favor of the United States upon ALL property and rights to property, whether real or personal, belonging to that person" },
  // ── EMPTY-AREA DISTILL batch 4 (NRA/withholding/PTI, estate inclusion+insurance+gift deductions, holding period, deficiency/CDP, AMT) ──
  { cite: "IRC §871", url: lii("871"), type: "statute", taxYear: [2024, 2025, 2026], note: "TAX ON NONRESIDENT ALIENS — a nonresident alien is taxed at a flat 30% (or lower treaty rate) on US-source FDAP income (fixed or determinable annual or periodical: interest, dividends, rents, royalties) that is NOT effectively connected with a US trade or business; income effectively connected is taxed at the graduated rates on a net basis" },
  { cite: "IRC §881", url: lii("881"), type: "statute", taxYear: [2024, 2025, 2026], note: "TAX ON FOREIGN CORPORATIONS — a foreign corporation is taxed at 30% (or treaty rate) on US-source FDAP income not effectively connected with a US trade or business; effectively connected income is taxed at the regular corporate rates (and may face the branch profits tax)" },
  { cite: "IRC §1441", url: lii("1441"), type: "statute", taxYear: [2024, 2025, 2026], note: "WITHHOLDING ON NONRESIDENT ALIENS — a withholding agent paying US-source FDAP income to a nonresident alien must deduct and WITHHOLD a 30% tax (reduced by an applicable treaty rate documented on a Form W-8); the agent is liable for tax not withheld" },
  { cite: "IRC §959", url: lii("959"), type: "statute", taxYear: [2024, 2025, 2026], note: "PREVIOUSLY TAXED INCOME (PTI) — earnings and profits of a CFC already included in a US shareholder's gross income under Subpart F or GILTI are EXCLUDED from income again when actually distributed; ordering rules track which E&P layers are PTI to prevent double taxation" },
  { cite: "IRC §2033", url: lii("2033"), type: "statute", taxYear: [2024, 2025, 2026], note: "PROPERTY IN WHICH THE DECEDENT HAD AN INTEREST — the gross estate includes the value of all property to the extent of the interest the decedent owned at the time of death" },
  { cite: "IRC §2042", url: lii("2042"), type: "statute", taxYear: [2024, 2025, 2026], note: "LIFE INSURANCE — the gross estate includes the proceeds of insurance on the decedent's life receivable by the executor, AND proceeds receivable by other beneficiaries if the decedent possessed at death any INCIDENTS OF OWNERSHIP (e.g., the power to change beneficiaries, borrow, or surrender)" },
  { cite: "IRC §2522", url: lii("2522"), type: "statute", taxYear: [2024, 2025, 2026], note: "GIFT-TAX CHARITABLE DEDUCTION — a deduction in computing taxable gifts for the value of property transferred to or for the use of qualifying charitable, religious, scientific, educational, or governmental organizations (with split-interest rules)" },
  { cite: "IRC §2523", url: lii("2523"), type: "statute", taxYear: [2024, 2025, 2026], note: "GIFT-TAX MARITAL DEDUCTION — an UNLIMITED deduction in computing taxable gifts for gifts to a spouse who is a US citizen (terminable-interest limits apply); for a NON-citizen spouse there is no marital deduction but an increased annual exclusion instead" },
  { cite: "IRC §1223", url: lii("1223"), type: "statute", taxYear: [2024, 2025, 2026], note: "HOLDING PERIOD — tacking rules: property with a substituted/carryover basis tacks the prior holding period; a gift tacks the donor's holding period; property acquired from a decedent (§1014 basis) is automatically treated as held LONG-TERM regardless of actual time held" },
  { cite: "IRC §6213", url: lii("6213"), type: "statute", taxYear: [2024, 2025, 2026], note: "DEFICIENCY PROCEDURES — before assessing a deficiency the IRS must mail a NOTICE OF DEFICIENCY (the 90-day letter); the taxpayer may petition the Tax Court within 90 days (150 if addressed outside the US), and assessment/collection is generally BARRED until the Tax Court decision is final" },
  { cite: "IRC §6330", url: lii("6330"), type: "statute", taxYear: [2024, 2025, 2026], note: "COLLECTION DUE PROCESS — before levying, the IRS must give written notice of the right to a CDP HEARING before an impartial Appeals officer, where the taxpayer may raise collection alternatives, spousal defenses, and (if no prior opportunity) the underlying liability; the determination is reviewable by the Tax Court" },
  { cite: "IRC §55", url: lii("55"), type: "statute", taxYear: [2024, 2025, 2026], note: "ALTERNATIVE MINIMUM TAX — imposes a tax equal to the excess of the TENTATIVE MINIMUM TAX over the regular tax; the tentative minimum tax is computed on alternative minimum taxable income (AMTI) above an exemption amount, at 26% / 28% for noncorporate taxpayers (a flat 15% corporate AMT on adjusted financial statement income for applicable corporations)" },
  { cite: "IRC §59", url: lii("59"), type: "statute", taxYear: [2024, 2025, 2026], note: "AMT — other definitions and special rules: the alternative minimum tax foreign tax credit, treatment of certain AMT items, and the rules coordinating the exemption phase-out and the minimum tax credit (§53)" },
  // ── EMPTY-AREA DISTILL batch 5 (outbound/§1248/deemed-credit, estate inclusion powers/joint/special-use, accounting cash/LIFO/LTC, collection/summons) ──
  { cite: "IRC §367", url: lii("367"), type: "statute", taxYear: [2024, 2025, 2026], note: "OUTBOUND TRANSFERS — overrides corporate nonrecognition: a US person's transfer of property to a FOREIGN corporation in a §351/§361 exchange triggers gain recognition (the foreign corporation is not treated as a corporation), with exceptions for active-business assets and gain-recognition agreements; §367(d) reaches transfers of intangibles" },
  { cite: "IRC §1248", url: lii("1248"), type: "statute", taxYear: [2024, 2025, 2026], note: "SALE OF CFC STOCK — gain on a US shareholder's sale or exchange of stock in a controlled foreign corporation is recharacterized as a DIVIDEND to the extent of the earnings and profits of the foreign corporation attributable to the stock accumulated while the shareholder held it" },
  { cite: "IRC §960", url: lii("960"), type: "statute", taxYear: [2024, 2025, 2026], note: "DEEMED-PAID FOREIGN TAX CREDIT — a domestic corporation that has a Subpart F or GILTI inclusion is treated as having PAID the foreign income taxes properly attributable to that inclusion, giving it an indirect foreign tax credit (subject to the §904 limitation and the GILTI haircut)" },
  { cite: "IRC §2035", url: lii("2035"), type: "statute", taxYear: [2024, 2025, 2026], note: "ADJUSTMENTS FOR GIFTS WITHIN 3 YEARS OF DEATH — the gross estate is increased by the GIFT TAX PAID on gifts made within 3 years of death (the gross-up rule), and certain transfers within 3 years of death (e.g., of life insurance or retained-interest property under §§2036-2038, 2042) are pulled back into the gross estate" },
  { cite: "IRC §2038", url: lii("2038"), type: "statute", taxYear: [2024, 2025, 2026], note: "REVOCABLE TRANSFERS — the gross estate includes property the decedent transferred where, at death, the enjoyment was subject to a power (alone or with another) to ALTER, AMEND, REVOKE, or TERMINATE the transfer" },
  { cite: "IRC §2040", url: lii("2040"), type: "statute", taxYear: [2024, 2025, 2026], note: "JOINT INTERESTS — the gross estate includes the FULL value of property held in joint tenancy with right of survivorship, EXCEPT the portion shown to be attributable to the surviving co-tenant's own contribution; for a QUALIFIED JOINT INTEREST between spouses, exactly one-half is included regardless of contribution" },
  { cite: "IRC §2041", url: lii("2041"), type: "statute", taxYear: [2024, 2025, 2026], note: "POWERS OF APPOINTMENT — the gross estate includes property over which the decedent held a GENERAL power of appointment at death (a power exercisable in favor of the decedent, the estate, or its creditors); a power limited by an ascertainable standard (health, education, support, maintenance) is NOT a general power" },
  { cite: "IRC §2032A", url: lii("2032A"), type: "statute", taxYear: [2024, 2025, 2026], note: "SPECIAL-USE VALUATION — qualified real property used in farming or a closely-held trade or business may be valued at its actual farm/business USE value rather than highest-and-best-use, reducing the gross estate by up to an inflation-indexed cap; recapture tax applies if the heir disposes of it or stops the qualified use within 10 years" },
  { cite: "IRC §448", url: lii("448"), type: "statute", taxYear: [2024, 2025, 2026], note: "LIMITATION ON CASH METHOD — C corporations, partnerships with a C-corp partner, and tax shelters generally may NOT use the cash receipts and disbursements method, EXCEPT a small business meeting the gross-receipts test (average annual gross receipts under an inflation-indexed threshold) and a qualified personal service corporation" },
  { cite: "IRC §460", url: lii("460"), type: "statute", taxYear: [2024, 2025, 2026], note: "LONG-TERM CONTRACTS — income from a long-term contract (not completed in the year entered) must generally be reported under the PERCENTAGE-OF-COMPLETION method with a lookback interest computation; exceptions exist for home-construction contracts and small construction contractors under the gross-receipts threshold" },
  { cite: "IRC §472", url: lii("472"), type: "statute", taxYear: [2024, 2025, 2026], note: "LIFO INVENTORY — a taxpayer may elect the last-in, first-out method of identifying inventory (newest costs to cost of goods sold first); if LIFO is used for tax, the LIFO CONFORMITY rule requires it also be used in financial statements issued to owners/creditors" },
  { cite: "IRC §6502", url: lii("6502"), type: "statute", taxYear: [2024, 2025, 2026], note: "COLLECTION AFTER ASSESSMENT — where an assessment has been timely made, the tax may be collected by levy or court proceeding only if begun within 10 YEARS after the assessment (the collection statute expiration date), subject to suspensions and agreed extensions" },
  { cite: "IRC §7602", url: lii("7602"), type: "statute", taxYear: [2024, 2025, 2026], note: "EXAMINATION AND SUMMONS AUTHORITY — to determine the correctness of a return or a tax liability, the IRS may examine books, papers, and records and may issue a SUMMONS compelling the taxpayer or third parties to appear, produce records, and give testimony under oath" },
  // ── EMPTY-AREA DISTILL batch 6 (TARGETED at the benchmark's remaining IRC gaps — gap-map driven) ──
  { cite: "IRC §121", url: lii("121"), type: "statute", taxYear: [2024, 2025, 2026], note: "EXCLUSION OF GAIN ON A PRINCIPAL RESIDENCE — a taxpayer may exclude up to $250,000 ($500,000 for a married couple filing jointly) of gain from the sale of a home owned AND used as the principal residence for at least 2 of the 5 years before the sale; the full exclusion is available only once every 2 years (a reduced exclusion applies for a sale due to a change in employment, health, or unforeseen circumstances)" },
  { cite: "IRC §108", url: lii("108"), type: "statute", taxYear: [2024, 2025, 2026], note: "DISCHARGE OF INDEBTEDNESS — cancellation-of-debt income is EXCLUDED from gross income if the discharge occurs in a Title 11 (bankruptcy) case, or while the taxpayer is INSOLVENT (limited to the amount of insolvency), or for qualified farm, real-property-business, or principal-residence indebtedness; excluded amounts REDUCE tax attributes (NOLs, credits, basis) under §108(b)" },
  { cite: "IRC §368", url: lii("368"), type: "statute", taxYear: [2024, 2025, 2026], note: "REORGANIZATIONS — defines the tax-free reorganization types: (A) statutory merger/consolidation, (B) stock-for-stock, (C) stock-for-substantially-all-assets, (D) divisive/acquisitive transfer to a controlled corp, (E) recapitalization, (F) mere change in identity/form, (G) bankruptcy; judicial doctrines of continuity of interest, continuity of business enterprise, and business purpose also must be met" },
  { cite: "IRC §381", url: lii("381"), type: "statute", taxYear: [2024, 2025, 2026], note: "CARRYOVERS IN CERTAIN ACQUISITIONS — in a §332 subsidiary liquidation or a §368 reorganization (A/C/D/F/G), the acquiring corporation SUCCEEDS TO and takes into account the target's enumerated tax attributes — net operating loss carryovers, earnings and profits, accounting methods, capital loss carryovers, and credits — subject to the §382/§383 limitations" },
  { cite: "IRC §1031", url: lii("1031"), type: "statute", taxYear: [2024, 2025, 2026], note: "LIKE-KIND EXCHANGES — no gain or loss is recognized on the exchange of REAL PROPERTY held for productive use in a trade or business or for investment for like-kind real property (post-2017, §1031 applies ONLY to real property, not personal property); receipt of money or non-like-kind property (BOOT) triggers gain; a deferred exchange must identify replacement property within 45 days and close within 180 days" },
  { cite: "IRC §453", url: lii("453"), type: "statute", taxYear: [2024, 2025, 2026], note: "INSTALLMENT METHOD — income from an installment sale (at least one payment received after the year of sale) is reported as payments are received: each payment's taxable gain equals the payment times the GROSS PROFIT RATIO (gross profit / total contract price); not available for inventory, dealer dispositions, or publicly traded property; §453A imposes interest on large deferred balances" },
  { cite: "IRC §1296", url: lii("1296"), type: "statute", taxYear: [2024, 2025, 2026], note: "PFIC MARK-TO-MARKET ELECTION — a US person owning MARKETABLE stock of a passive foreign investment company may ELECT to include annually in ordinary income the excess of year-end fair market value over adjusted basis (and deduct decreases, limited to prior mark-to-market gains), as an alternative to the §1291 interest-charge regime" },
  { cite: "IRC §663", url: lii("663"), type: "statute", taxYear: [2024, 2025, 2026], note: "SPECIAL RULES FOR TRUST/ESTATE DISTRIBUTIONS — §663(a)(1): a gift or bequest of a SPECIFIC sum of money or specific property paid in three or fewer installments does NOT carry out distributable net income (DNI); §663(b): a trust or estate may ELECT to treat distributions made within the first 65 DAYS of the year as paid on the last day of the preceding year" },
  { cite: "IRC §2632", url: lii("2632"), type: "statute", taxYear: [2024, 2025, 2026], note: "ALLOCATION OF THE GST EXEMPTION — a transferor's GST exemption is AUTOMATICALLY allocated to direct skips, and to indirect skips to a GST trust, unless the transferor elects out; an allocation may also be made on a gift-tax return; the allocation determines the trust's inclusion ratio (and thus its exposure to GST tax)" },
  { cite: "IRC §6501", url: lii("6501"), type: "statute", taxYear: [2024, 2025, 2026], note: "ASSESSMENT STATUTE OF LIMITATIONS — tax must generally be ASSESSED within 3 YEARS after the return is filed (or its due date if later); the period is 6 YEARS if there is a substantial omission of gross income (more than 25%); and there is NO time limit for a false or fraudulent return, a willful attempt to evade, or a failure to file" },
  { cite: "IRC §4958", url: lii("4958"), type: "statute", taxYear: [2024, 2025, 2026], note: "EXCESS BENEFIT TRANSACTIONS (intermediate sanctions) — a 25% excise tax is imposed on a DISQUALIFIED PERSON who receives an excess economic benefit from a §501(c)(3) or (c)(4) organization (200% additional tax if not corrected), plus a 10% tax on organization managers who knowingly approved the transaction; a rebuttable presumption of reasonableness applies if proper procedures are followed" },
  { cite: "IRC §513", url: lii("513"), type: "statute", taxYear: [2024, 2025, 2026], note: "UNRELATED TRADE OR BUSINESS — any trade or business the conduct of which is not SUBSTANTIALLY RELATED (aside from the need for funds) to the organization's exempt purpose; EXCLUDED are a business in which substantially all the work is done by volunteers, one carried on for the convenience of members/students/patients, and the selling of donated merchandise" },
  { cite: "IRC §41", url: lii("41"), type: "statute", taxYear: [2024, 2025, 2026], note: "CREDIT FOR INCREASING RESEARCH ACTIVITIES — a credit equal to 20% of the excess of qualified research expenses over a base amount, OR the alternative simplified credit of 14% of QRE over 50% of the average QRE for the prior 3 years; qualified research expenses are in-house wages and supplies for qualified research plus 65% of contract research expenses" },
  // IRC §1202 (QSBS) — DISABLED pending a fix. The figure-grounded chunk is correct on the tiers
  // but the LII operative text refers to "the applicable date" WITHOUT pinning it to a calendar date,
  // and the "OBBBA enacted July 4, 2025" fact lives in a chunk a QSBS query doesn't co-retrieve. Result:
  // the model can't place a pre-July-2025 acquisition and CONFIDENTLY MISCLASSIFIES it (gave 75% where
  // the answer is $0 for a 4-yr hold on March-2025 stock). A confident wrong answer is worse than the
  // honest abstain, so this stays out until the applicable-date definition (= OBBBA enactment, 7/4/2025)
  // is grounded INTO this chunk and/or co-retrieved. See ask-once.mts to reproduce.
  // { cite: "IRC §1202", url: lii("1202"), type: "statute", taxYear: [2025, 2026], note: "QSBS gain exclusion — capture the applicable-date DEFINITION (= date of enactment of OBBBA / P.L. 119-21) explicitly, not just the term." },
];

// A figure's NUMERIC CORE (digits only) — so "3.8%", "3.8 percent", and "$3.8" all compare equal,
// and "$125,000" matches "125,000". The gate grounds the NUMBER, tolerant of unit formatting.
function figureCores(text: string): string[] {
  return [...text.matchAll(/\$?\d[\d,]*(?:\.\d+)?\s?%?|\b(?:19|20)\d{2}\b/g)]
    .map((m) => m[0].replace(/[^\d.]/g, ""))
    .filter((n) => n.length >= 2 && n !== "."); // ignore single digits / noise
}
function norm(s: string): string { return s.replace(/[^\d.]/g, ""); } // digits-and-dots stream of the source

async function fetchSource(url: string, anchor?: string): Promise<string> {
  const res = await fetch(url, { headers: { "user-agent": "PetalAuthorityIngest/1.0 (tax-research corpus)" } });
  if (!res.ok) throw new Error(`fetch ${res.status}`);
  const raw = await res.text();
  // Strip scripts/styles/tags to plain text; collapse whitespace.
  const stripped = raw
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&[a-z]+;/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
  // RE-CENTER the 24000-char window on the cited rule when it's buried past the cap (the §163(j)/§1.409A-1
  // fix) — keeps the distill grounded in the ACTUAL subsection instead of letting the cap drop it.
  if (anchor) {
    const i = stripped.toLowerCase().indexOf(anchor.toLowerCase());
    if (i >= 0) { const start = Math.max(0, i - 4000); return stripped.slice(start, start + 24000); }
    throw new Error(`anchor not found: "${anchor.slice(0, 40)}"`); // fail loud, don't silently ingest the wrong window
  }
  return stripped.slice(0, 24000);
}

const SYS = `You ingest US tax PRIMARY AUTHORITY into a research corpus. From the provided source text of ONE provision, write a single concise "operative rule" paraphrase a tax preparer could rely on. RULES: use ONLY facts/figures present in the provided text — never add a number, threshold, rate, or year from your own knowledge; if the text doesn't state a figure, don't include it. Public-domain factual paraphrase (statute isn't copyrightable). Output STRICT JSON only: {"text": string (the operative-rule paraphrase, 2-5 sentences), "keywords": string[] (8-15 lowercase retrieval terms incl. the section number and key concepts), "effectiveDate": "YYYY-MM-DD" (when this rule took effect; use the provided text or a conservative Jan 1 of the earliest listed tax year)}.`;

async function buildChunk(t: Target, provider: AIProvider): Promise<AuthorityChunk | null> {
  const source = await fetchSource(t.url, t.anchor);
  const { text: out } = await provider.generateText({
    system: SYS,
    prompt: `Citation: ${t.cite}\nHint: ${t.note}\nTax years this should serve: ${t.taxYear.join(", ")}\n\nSOURCE TEXT:\n${source}`,
    maxTokens: 700,
  });
  let parsed: { text: string; keywords: string[]; effectiveDate: string };
  try { parsed = JSON.parse(out.slice(out.indexOf("{"), out.lastIndexOf("}") + 1)); }
  catch { console.log(`✗ ${t.cite}: non-JSON output`); return null; }

  // GROUNDING GATE: every figure's numeric core in the paraphrase must appear in the fetched source.
  const src = norm(source);
  const ungrounded = figureCores(parsed.text).filter((f) => !src.includes(f));
  if (ungrounded.length) { console.log(`✗ ${t.cite}: ungrounded figures ${ungrounded.join(", ")} (rejected)`); return null; }

  const chunk: AuthorityChunk = {
    chunkId: `ingested-${t.cite.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    authorityType: t.type,
    citation: t.cite,
    jurisdiction: "federal",
    taxYear: t.taxYear,
    effectiveDate: parsed.effectiveDate || `${Math.min(...t.taxYear)}-01-01`,
    sourceUrl: t.url,
    ingestedAt: new Date().toISOString(),
    text: parsed.text,
    keywords: [...new Set(parsed.keywords.map((k) => k.toLowerCase()))],
    // Post-Loper-Bright delegation strength — wakes the §6662 weighting engine's DELEGATION_FACTOR for regs.
    ...(t.delegationBasis ? { delegationBasis: t.delegationBasis } : {}),
  };
  const v = authorityChunkSchema.safeParse(chunk);
  if (!v.success) { console.log(`✗ ${t.cite}: schema ${v.error.issues[0]?.message}`); return null; }
  console.log(`✓ ${t.cite}: ${chunk.text.slice(0, 90)}…`);
  return chunk;
}

async function main() {
  const write = process.argv.includes("--write");
  // Optional section filter: non-flag args restrict which TARGETS run (e.g. `... 30D 6050W`). With
  // --write + a filter, the new chunks are MERGED into the existing corpus (existing ones kept, not
  // re-paraphrased); with --write and no filter, the whole file is regenerated from all TARGETS.
  const only = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  // EXACT section match (not substring) — "312" must select ONLY §312, never §3121; required for safe BULK runs.
  // Strips the IRC / Treas. Reg. prefix so a reg arg like "1.6662-4" selects "Treas. Reg. §1.6662-4".
  const sectionOf = (cite: string) => cite.replace(/^(IRC|Treas\.?\s*Reg\.?|Reg\.?|Prop\.?\s*Reg\.?)\s*§?\s*/i, "").trim().toLowerCase();
  const targets = only.length ? TARGETS.filter((t) => only.some((o) => sectionOf(t.cite) === o.toLowerCase())) : TARGETS;
  // Provider via the FACTORY so ingestion honors PETAL_DEV_INFERENCE=codex-sub (runs on the codex sub, not
  // the metered Anthropic key). The figure-grounding gate below guards correctness regardless of model.
  const provider = getProvider("claude-sonnet-4-6");
  const out: AuthorityChunk[] = [];
  for (const t of targets) {
    try { const c = await buildChunk(t, provider); if (c) out.push(c); }
    catch (e) { console.log(`✗ ${t.cite}: ${e instanceof Error ? e.message : e}`); }
  }
  console.log(`\n${out.length}/${targets.length} chunks passed the grounding gate.`);

  if (write) {
    // Merge into the existing corpus when a filter was used (keep the others); else full regenerate.
    let final = out;
    if (only.length) {
      const { CORPUS_INGESTED } = (await import("../lib/research/corpus-ingested.ts")) as { CORPUS_INGESTED: AuthorityChunk[] };
      const byId = new Map(CORPUS_INGESTED.map((c) => [c.chunkId, c]));
      for (const c of out) byId.set(c.chunkId, c);
      final = [...byId.values()];
    }
    const { writeFileSync } = await import("node:fs");
    const file =
      `// AUTO-GENERATED by scripts/ingest-authority.mts — re-run to refresh; do not hand-edit.\n` +
      `// Grounded primary-authority chunks: each is a concise operative-rule paraphrase produced\n` +
      `// FROM the fetched source text, and every $/%/year figure was verified to appear in that\n` +
      `// source before admission. Public domain (statute) — §7216-clean. Registered in authority/store.ts.\n` +
      `import type { AuthorityChunk } from "../tax/authority/store";\n\n` +
      `export const CORPUS_INGESTED: AuthorityChunk[] = ${JSON.stringify(final, null, 2)};\n`;
    writeFileSync("lib/research/corpus-ingested.ts", file);
    console.log(`wrote lib/research/corpus-ingested.ts (${final.length} chunks)`);
  } else {
    console.log("(dry run — pass --write to emit lib/research/corpus-ingested.ts)");
  }
}
main().catch((e) => { console.error(e); process.exit(1); });
