export const notifications = [
  {
    id: 1,
    title: "Priya Sharma uploaded a document",
    desc: "1099-NEC from TikTok uploaded to portal. Ready for extraction.",
    avatar: "/images/avatars/02.png",
    status: "online",
    unread_message: true,
    type: "text",
    date: "10 min ago",
    clientId: "c2",
  },
  {
    id: 2,
    title: "David Park rescheduled",
    desc: "S-Corp review call moved to 3:00 PM today.",
    avatar: "/images/avatars/11.png",
    status: "online",
    unread_message: true,
    type: "text",
    date: "25 min ago",
    clientId: "c11",
  },
  {
    id: 3,
    title: "Rodriguez signed 8879",
    desc: "James & Sofia both signed. Your ERO countersignature needed to file.",
    avatar: "/images/avatars/03.png",
    status: "online",
    unread_message: true,
    type: "confirm",
    date: "1 hour ago",
    clientId: "c3",
  },
  {
    id: 4,
    title: "Payment: Aisha Johnson — $350",
    desc: "Full balance paid via Stripe. Return ready for ERO signature.",
    avatar: "/images/avatars/02.png",
    status: "online",
    unread_message: false,
    type: "text",
    date: "2 hours ago",
    clientId: "c14",
  },
  {
    id: 5,
    title: "Stale: Tyrone Mitchell — 9 days",
    desc: "2 of 5 docs submitted. No portal activity since Mar 19.",
    avatar: "/images/avatars/05.png",
    status: "busy",
    unread_message: true,
    type: "text",
    date: "This morning",
    clientId: "c17",
  },
  {
    id: 6,
    title: "Carlos Mendez sent a message",
    desc: "Paint booth deduction question from Elena.",
    avatar: "/images/avatars/03.png",
    status: "online",
    unread_message: false,
    type: "text",
    date: "Yesterday",
    clientId: "c15",
  },
  {
    id: 7,
    title: "Extension likely: Vladimir Petrov",
    desc: "0 of 16 docs. Never logged in. Complex international.",
    avatar: "/images/avatars/01.png",
    status: "busy",
    unread_message: false,
    type: "text",
    date: "Yesterday",
    clientId: "c13",
  },
];

export type Notification = (typeof notifications)[number];
